### ISSUE TITLE
GSoC Workspace: Implement `WASI` and `wasmedge_process` host functions on the Windows platform

### ISSUE THREAD

**Issue by abhinandanudupa** [WasmEdge/WasmEdge#1477]
# Motivation

Currently, the `WASI` and `wasmedge_process` components in WasmEdge are only implemented on *nix platforms (mac OS and Linux) and most of the host functions are not yet supported on the Windows platform. Since there are a lot of windows users would like to use `WasmEdge`, it will be important to implement these host functions and satisfy their requirements.

# Milestones

### Community bonding period [20th May, 2022 to June 12th, 2022]
* [x] Setup the working environment (Windows SDK v`19041`).
* [x] Understand the existing code base and the requirements
* [x] List out the milestones to be achieved - you know once you start

### Coding Period [13th June, 2022 to 12th September, 2022]
* [x] ~Implement `DirHolder` using the `Win32` API~ -  not necessary as `HandleHolder` should be sufficient
* [x] Implement a function to map file constants/flags from `win32 API` to `WASI`/`*nix` 
    - `attributeFlags()` - maps file attributes to `WASI`, flags to manage file attributes/types
    - `accessFlags()` - maps access flags to `WASI`, flags to define permissions on the file for the user/process
    - `shareFlags()` - maps share flags to `WASI`, flags to allow other processes to read or to write to the open file
    - `creationDisposition()` - maps creation disposition flags to `WASI`, flags to truncate or to create a new file
* [x] Implement a function to map error codes from `win32 API` to `WASI` [`fromWinError()`]
* [x] Implement a function to convert a signed 64 bit integer to a `LARGE_INTEGER` [`toLargeIntegerFromUnsigned()`]
* [x] Implement a function to convert a unsigned 64 bit integer to a `LARGE_INTEGER` [`toLargeIntegerFromSigned()`]
* [x] Implement a function to map file types to `WASI` [`fromFileType()`]
* [x] Implement a function to define the relatively position of the file pointer during a read or write operation [`fromWhence()`]
* [x] Implement host functions as defined and described in [`include/host/wasi/indoe.h`](https://github.com/WasmEdge/WasmEdge/blob/master/include/host/wasi/inode.h#L182)
* [x] Implement the host functions!

# How I think I would implement the functions

I think it will be a good thing to learn the Linux implementations, find equivalent functions and then implement with `win32 API`. I would not have to go build from scratch (hopefully) and reduce the time taken.

### A. WASI component
- Go through the code in the  [lib/host/wasi](https://github.com/WasmEdge/WasmEdge/tree/master/lib/host/wasi) and understand the requirements.
- Try understanding the host functions that were implemented for the *nix Operating systems.
- Implement all unimplemented functions that return `WasiUnexpect(__WASI_ERRNO_NOSYS)` or `false`.
- Pass all unit tests.

### B. WASMEDGE_PROCESS component
- Go through the files in [plugins](https://github.com/WasmEdge/WasmEdge/tree/master/plugins) and understand the requirements.
- Different OSes use different libraries for C/C++ - Linux uses `Glibc` but windows has it's own libraries. We will have to implement the OS specific functions and split the files in to the corresponding header files as in WASI using the `Win32` API.

# Status

I have completed most of the functions described by the `WASI` but some functions may may issues. `Poller::*()` functions need Windows to have a similar API and as far as I know there is no such API. It seems that other `WASM` runtimes have implemented functions that repeatedly check if the operations has completed or not. Windows does not seem to have an appropriate API to query the status of many I/O operations.

### Causes
- Certain flags do not have a equivalent in the Win32 API.
- Many POSIX functions do not have  an equivalent on windows.
- Windows uses ACL but POSIX does not.

### Descriptions
- `open()`: to use the flag `__WASI_FDFLAGS_NONBLOCK` we have to used an `OVERLAPPED` structure to query the status of the read/write operation. But in the API we do not describe an a function which queries the status  of the operation. Hence files opened with this flags do not have a way to query that status of the operation.
- `fdAdvise()`: we do not have a direct equivalent for this function in the Win32 API but we can use certain file flags [`FILE_FLAG_RANDOM_ACCESS`, `FILE_FLAG_SEQUENTIAL_SCAN`, `OPEN_EXISTING`]with the `CreateFile()` and functions like [`PrefetchVirtualMemory()`](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-prefetchvirtualmemory?redirectedfrom=MSDN) and use certain flags in the read/write functions - `ReadFile` and `WriteFile`.
- `fdAllocate()`: signed bit has to be removed as the parameter `Offset` and `Len` are unsigned.
- `fdDatasync()`: it seems that meta data will be [flushed only when the `Handle` is opened with certain attributes](https://devblogs.microsoft.com/oldnewthing/20210729-00/?p=105494).
- `fdFdstatGet()`: need to find appropriate flags for the fields - `fs_rights_base` and `fs_rights_inheriting` and file types for `fs_filetype`. The linux implementation does not fill the `*rights*` fields.
- `fdFdstatSetFlags()`: the `__WASI_FDFLAGS_APPEND` flag can be safely ignored.
- `fdFilestatGet`: need to find equivalent file types, three are missing. And there is no equivalent for device ID and INode number.
- `fdFilestatSetSize()`: does not set the extra bytes to zero.
- `fdPread`: does not support asynchronous operation as the the function is similar to `preadv` which is subject to the `O_NONBLOCK` flag as according to the [source](https://man7.org/linux/man-pages/man2/open.2.html)
```
              Note that this flag has no effect for regular files and
              block devices; that is, I/O operations will (briefly)
              block when device activity is required, regardless of
              whether O_NONBLOCK is set.  Since O_NONBLOCK semantics
              might eventually be implemented, applications should not
              depend upon blocking behavior when specifying this flag
              for regular files and block devices.
```
- `fdReaddir()`: might require some optimisation.
- `fdSync()`: same as that for `fdDatasync`.
- `pathFilestatGet()`: there is no equivalent for device number and the INode number.
- `filetype()`: need to find equivalent flags for the file types.
- `unsafeFiletype()`: same as above - need to find equivalent flags for the file types.

## wasmedge_process
- Yet to implement host specific functions in [`plugins/wasmedge_process/processfunc.cpp`](https://github.com/WasmEdge/WasmEdge/blob/master/plugins/wasmedge_process/processfunc.cpp)

**Comment by abhinandanudupa** [comment]
## Community Bonding Period [20th May, 2022 to June 12th, 2022] - status update
- LLVM coding style has to be followed - [.clang-format](https://github.com/WasmEdge/WasmEdge/blob/master/.clang-format) and [.clang-tidy](https://github.com/WasmEdge/WasmEdge/blob/master/.clang-tidy)
- Use `GDB`to trace the execution flow for a WASI function invoke and learn from it
- Many flags like `O_CREAT`, `O_TRUNC` may not have an equivalent in the `Win32` API and these missing flags should be logged
- There are many definitions like `__wasi_fdflags_` which if need to be updated have to be generated from [/utils/wasi-cpp-headers](https://github.com/WasmEdge/WasmEdge/tree/master/utils/wasi-cpp-header) and generate the [`api.hpp`](https://github.com/WasmEdge/WasmEdge/blob/master/thirdparty/wasi/api.hpp) file. These are important in 
- Since Windows uses `FILE` and `DIRECTORY` `HANDLE`s while *nix uses File Descriptors we will have to build define new definitions for `DirHolder`, `TimeHolder` and others. This will be the starting point for this project.
- The `wasmedge_process` has been implemented as a plugin now and we will have to implement host functions for it, using the `Win32` API

**Comment by abhinandanudupa** [comment]
## Proposal: Use `Microsoft CRT` (UCRT) instead of the  `win32 API`

### Introduction
The Universal C Runtime Library (UCRT) supports most of the C standard library required for C++ conformance. It implements the C99 (ISO/IEC 9899:1999) library, with certain exceptions. It is somewhat POSIX compliant - implements most of the `POSIX.1 (ISO/IEC 9945-1:1996, the POSIX System Application Program Interface) C library`.
Reference: [Compatibility](https://docs.microsoft.com/en-us/cpp/c-runtime-library/compatibility?view=msvc-170)

## Motivation
`WasmEdge` uses _*nix like_ file/IO handling. Many of the internal functions and data structures that it uses are influenced by  *nix like systems which is _POSIX_ compliant. _*nix like_ OSes have a System Application Interface specification that defines many of the behaviours and data structures to provide a uniform API for developers which is portable and well documented. 

Windows not being a _*nix like_ OS has it's own implementations for file/IO handling which are defined in the [`Win32 API`](https://docs.microsoft.com/en-us/windows/win32/api/). This API not POSIX compliant and do not have equivalent functions/data structures/specifications that could be easily ported to `WasmEdge`.

Using the `Win32 API` for implementing host functions on Windows would lead to developing two different sets of code for the two different classes of Operating systems - Windows and *nix like OSes, for the same functionality. This is not appropriate when we have the Microsoft C Runtime which provides most of the required functions for `WasmEdge`.

## Expected Outcomes
- We will be able to port the logic for _*nix like_ OSes to Windows easily.
- We reduce the need to maintain two different sets of code for the platforms, which is a bad practice
- The development cycle can go faster
- Many flags, signals and functions that `WasmEdge` uses may not have an appropriate equivalent in the `Win32 API`. For example checkout the following links: [WasmEdge](https://github.com/WasmEdge/WasmEdge/blob/master/lib/host/wasi/inode-linux.cpp#L47-L109), [CRT](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/sopen-s-wsopen-s?view=msvc-170#generic-text-routine-mappings), Win32 API - [access rights](https://docs.microsoft.com/en-us/windows/win32/fileio/file-access-rights-constants) and [attributes](https://docs.microsoft.com/en-us/windows/win32/fileio/file-attribute-constants)

## Possible Issues
- The performance _may be_ an issue. A lot of the functions are just wrappers around the `Win32 API` functions and some others are directly implemented in the kernel like `memcpy`. (I have not found any concrete performance comparison of the libraries yet)
- _will be updated if found later_

## References
https://docs.microsoft.com/en-us/cpp/c-runtime-library/c-run-time-library-reference?view=msvc-170
https://docs.microsoft.com/en-us/cpp/c-runtime-library/run-time-routines-by-category?view=msvc-170
https://docs.microsoft.com/en-us/cpp/c-runtime-library/error-handling-crt?view=msvc-170
https://docs.microsoft.com/en-us/cpp/c-runtime-library/compatibility?view=msvc-170

https://docs.microsoft.com/en-us/windows/win32/api/
https://docs.microsoft.com/en-us/windows/win32/fileio/file-management

https://www.codeproject.com/Articles/22642/What-Every-Computer-Programmer-Should-Know-About-W#CRuntimeLibrary

**Comment by hydai** [comment]
I have some questions about your proposal:

1. `We will be able to port the logic for *nix like OSes to Windows easily.`. However, not all of the libc functions are implemented in CRT. If you do want to use this, please identify if the CRT covers all of the functions that we may use.
2. `We reduce the need to maintain two different sets of code for the platforms, which is a bad practice`. Actually, we should care about the cross-platform issue, not the CRT does. AFAIK, the CRT is not completely using the Windows API, so it may have several performance issues. That's why we are trying to use the `Win32 API` directly not the CRT.

According to the above opinions, you may need to have more evidence to convince me to switch to the `CRT`.

Not sure if you have looked at `cppwinrt`, that should be a C++17 compliant WinRT API.

**Comment by abhinandanudupa** [comment]
> 1. `We will be able to port the logic for *nix like OSes to Windows easily.`. However, not all of the libc functions are implemented in CRT. If you do want to use this, please identify if the CRT covers all of the functions that we may use.

I will work on this today.

> 2. `We reduce the need to maintain two different sets of code for the platforms, which is a bad practice`. Actually, we should care about the cross-platform issue, not the CRT does. AFAIK, the CRT is not completely using the Windows API, so it may have several performance issues. That's why we are trying to use the `Win32 API` directly not the CRT.

I will try to find more information on this and if you think the performance impact is not acceptable, then we will use `win32 API` itself.

> Not sure if you have looked at `cppwinrt`, that should be a C++17 compliant WinRT API.

`cppwinrt` is a language projection that is designed to bring natural, idiomatic language patterns to the windows runtime through wrapper classes. But we are focusing on the underlying API calls because of which I did not focus on it. 

I referred to this 
https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/
https://stackoverflow.com/questions/60021694/what-is-c-winrt-exactly

**Comment by abhinandanudupa** [comment]
### List of functions used in the Linux implementation which are available in the windows Universal C Runtime:
- `_open()` [`open()` equivalent] - missing flags: `O_DIRECTORY`, (`O_SYNC`, `O_DSYNC`, `O_RSYNC`), `O_NONBLOCK`, `O_CLOEXEC`, `NO_FOLLOW`
- `_futime()` [`futimens` equivalent]
- `_read()` [ `readv()` equivalent]
- `_lseek()` [`lseek()` equivalent]
- `_write()` [`writev` equivalent]
- `_dup()` [`dup()` equivalent]
- `_rename()` [`rename()` equivalent]
- `_fstat()` [`fstat()` equivalent]


### Can be used with a workaround?
- `mkdirat()` - this function creates a directory relative to a file descriptor, but a work around should be found
- `fstatat()` -  fetches information about a file if a relative path is given, but a work around should be found
- `utimensat()` - needs a file descriptor
- `openat()` - open a file from relative path but a workaround should be found
- `clock_gettime` - get the system wide clock time but other functions should be available
- `futimes()` - changes access and modification times of a file specified by a function descriptor, workaround should be found
- `linkat()` - creates a hard link with a relative path to a file maybe another function exists?
- `unlinkat()` - un-links/delete a file when a relative path is given, workaround should be found

#### Possible Workarounds
1. For functions needing the file descriptor we can refer to the file it is trying to change by path and then using the other equivalent function which uses a path
2. For functions using the relative path, we should be able to get the corresponding absolute path from the `HandleHolder`

### Missing functions:
- `posix_fallocate()`
- `fdatasync()`
- `fcntl()`
- `ftruncate()`
- `preadv()`
- `pwritev()`
- `fsync()`
- `symlinkat()`
- `epoll_ctl()`


Functions that I am not sure about (probably WasmEdge functions):
- `updateState()`

**Comment by abhinandanudupa** [comment]
#### Possible Performance Issues with `Universal CRT`
Unfortunately, I have not found any information regarding the performance of the library in comparison to the `win32 API`. I really tried hard but could only find two stack overflow questions somewhat vaguely mentioning about this and contradicting each other. Even Microsoft has not mentioned about the performance of this API any where in their documentation even though the library is official.


In the absence of concrete evidence, I think I will continue with the `win32 API`.

**Comment by abhinandanudupa** [comment]
### Function-wise Summary

Note: WFL -> Will Fix Later

| Function | Status | Comment |
| ---------------- | ---------------- | ---------------- |
| `open` | complete | None |
| `fdAdvise` | no equivalent | WFL |
| `fdAllocate` | complete | None |
| `fdDatasync` | complete | None |
| `fdFdstatGet` | incomplete | Need to find equivalent flags |
| `fdFdstatSetFlags` | incomplete | need to get file attributes and flags from `handle` |

It has been difficult to map `Win32` functions to `WASI` functions, many flags and attributes don't have an equivalent and the logic for the function will have to involve many helper functions which retrieve and map attributes and flags to those used by `WasmEdge`.

**Comment by abhinandanudupa** [comment]
Hi @LFsWang !
There seems to be an issue in loading plugins on Windows and for this I need to set up a debug environment. I have tried to use MS Visual Studio code's debugger but I ran into issues. Can you please tell me how you set your debug environment and what tools do you use on windows to debug WasmEdge?
