### ISSUE TITLE
LFX Workspace: Support Durable Objects (DO) in WasmEdge

### ISSUE THREAD

**Issue by richardchien** [WasmEdge/WasmEdge#1525]
## Motivation

Durable Objects (DO) are persistent data objects available to applications at runtime. They can be stored in a persistent KV store or a data cache. [DOs are important for stateful serverless functions](https://blog.cloudflare.com/introducing-workers-durable-objects/).

The [Anna KVS](https://github.com/hydro-project/anna) project developed by UC Berkeley is an autoscaling KVS ideally suited for edge nodes. It is a good match for WasmEdge to support stateful serverless functions on the edge cloud. The goal of this task is to create Rust and JavaScript clients for Anna KVS using the WasmEdge socket API. It allows Rust-based WasmEdge applications to connect to Anna KVS, and store or retrieve DOs in the KVS.

Note: A new Rust-based version of Anna KVS is going to be released soon. We will likely use the new version for this task. The network socket API for accessing the KVS will remain largely unchanged from the old version.

## Milestone

- [ ] Make Tokio `TcpStream` work on top of WasmEdge Socket API (adaptation is needed for [mio](https://github.com/tokio-rs/mio)).
- [ ] Port [zmq.rs](https://github.com/zeromq/zmq.rs) to WasmEdge, making the ZeroMQ client library work.
- [ ] Port [rust-protobuf](https://github.com/stepancheg/rust-protobuf) or [prost](https://github.com/tokio-rs/prost) to WasmEdge.
- [ ] Implement [Lattice](https://github.com/hydro-project/common/tree/master/include/lattices) types in Rust.
- [ ] Rewrite [Anna KVS client](https://github.com/hydro-project/common/blob/master/include/client/kvs_client.hpp) in Rust.

**Comment by richardchien** [comment]
Since [anna-rs](https://github.com/essa-project/anna-rs), the new Anna KVS written in Rust, was made public a few days ago, the specification of this task should be adjusted. After some investigation, I found that most of the Rust code of anna-rs can be reused to implement an Anna client on top of WasmEdge. In fact, this task will be something like just porting anna-rs to WasmEdge, with some adaptation needed.

The new anna-rs uses:

1. [async-net](https://github.com/smol-rs/async-net), which is part of [smol](https://github.com/smol-rs/smol), to do TCP connections;
2. [zenoh](https://github.com/eclipse-zenoh/zenoh) as the message queue to communicate between client and routing nodes, which uses `async_std::net::TcpStream` to do TCP;
3. serde to serialize and deserialize messages sent between nodes.

So I think the main jobs of this task will be adapt smol (async-net) and async_std to use [wasmedge_wasi_socket](https://github.com/second-state/wasmedge_wasi_socket) as their underlying socket implementation. Milestones have been adjusted accordingly.

**Comment by richardchien** [comment]
After some digging, I found it possible to get rid of Zenoh in anna-rs's client code, so that it can talk to routing nodes and kvs nodes through vanilla TCP connections, thanks to the built-in TCP support of anna-rs. The adapted client is put [here](https://github.com/richardchien/anna-client-tokio), temporarily. After it's done, I will move it to WasmEdge org.

The routing nodes originally use TCP ports dynamically allocated by system, so we have to do a little [modification](https://github.com/richardchien/anna-rs) to it so that the client can find routing nodes deterministically, by specifying the ports in config file.

Milestone progress has been updated accordingly.

**Comment by juntao** [comment]
Does our approach depend on Tokio support in WasmEdge? 

Perhaps we can create a prototype example using `wasmedge_http_req` first. We can switch the async Tokio MIO-like API once #1532 is ready?

**Comment by richardchien** [comment]
> Perhaps we can create a prototype example using `wasmedge_http_req` first. We can switch the async Tokio MIO-like API once #1532 is ready?

Do you mean using `wasmedge_wasi_socket`? The anna-rs client code is mostly async, while `wasmedge_wasi_socket` is nonblocking but not async. I don't think it will be easy to adapt anna-rs client to be non-async, at least won't be easier than adapt it to use Tokio.

Since basic functions of Tokio already works on WasmEdge according to #1532, I suggest we try to quickly adapt anna-rs client to use Tokio, and see if it can work or not. It may only take a weekend or so to do this. If it doesn't work then, we can consider rewrite the client in non-async manner or solve the problem of Tokio together with @MediosZ.

**Comment by juntao** [comment]
Ok. Let's try WasmEdge tokio + mio then!

**Comment by richardchien** [comment]
Now [anna-client-tokio](https://github.com/richardchien/anna-client-tokio) uses Tokio instead of smol. It currently only works on my host system (macOS), still has some issues when running on WasmEdge. The next step is to do necessary debug and modification to make it work on WasmEdge.

**Comment by juntao** [comment]
This is great! Is the README for the anna-client-tokio project accurate? Thanks. 

> Now [anna-client-tokio](https://github.com/richardchien/anna-client-tokio) uses Tokio instead of smol. It currently only works on my host system (macOS), still has some issues when running on WasmEdge. The next step is to do necessary debug and modification to make it work on WasmEdge.

**Comment by richardchien** [comment]
> Is the README for the anna-client-tokio project accurate? Thanks. 

No it's the original readme of anna-rs, I will rewrite it later.

**Comment by juntao** [comment]
Got it. Does you client support all anna operations (GET, PUT, PUT-SET) right now?

**Comment by richardchien** [comment]
> Got it. Does you client support all anna operations (GET, PUT, PUT-SET) right now?

Yes, it has all functionalities the original Anna client has.

**Comment by richardchien** [comment]
After some debugging, I decided to rewrite the TCP sending and receiving logic of Anna Rust client instead of directly run the original client on WasmEdge, because the `futures::select!`, `FusedStream`, `FuturesUnordered` stuffs cannot work properly with Tokio for WasmEdge. It seems there's some incompatibility between `futures` and `tokio` on our Tokio for WasmEdge. Rewriting is not a huge work though, since it's also in async fashion and most code can be reused.

Now we can `GET` and `PUT` values from Anna inside WASM modules running on WasmEdge! Code is like:

```rust
// Load config
let config: Config = argh::from_env();
log::info!("Loaded config from command line args: {:?}", config);

// Create Anna client
let routing_threads: Vec<_> = (0..config.routing_threads)
    .map(|i| RoutingThread::new(i))
    .collect();
let timeout = Duration::from_secs(10);
let mut client = ClientNode::new(
    format!("client-{}", uuid::Uuid::new_v4()),
    0,
    routing_threads,
    timeout,
)?;

// Put value
client
    .put_lww("time".into(), format!("{}", chrono::Utc::now()).into())
    .await?;
log::info!("Successfully PUT `time`");

tokio::time::sleep(Duration::from_secs(1)).await;

// Get value
let value = String::from_utf8(client.get_lww("time".into()).await?)?;
log::info!("Successfully GET `time`: {}", value);
```

Later I will continue to improve the client code to increase reuse of code and TCP connections.

**Comment by juntao** [comment]
Thanks Richard. Does that mean that there is now a separate repo and crate for "WasmEdge Anna client"? Can you point us to it? Thanks.

**Comment by richardchien** [comment]
> Thanks Richard. Does that mean that there is now a separate repo and crate for "WasmEdge Anna client"? Can you point us to it? Thanks. 

It's still in [anna-client-tokio](https://github.com/richardchien/anna-client-tokio). I just put my rewritten client in a new Rust file.

**Comment by juntao** [comment]
I saw that it still uses regular tokio not the WasmEdge fork of tokio. Can it run inside WasmEdge now?

**Comment by richardchien** [comment]
> I saw that it still uses regular tokio not the WasmEdge fork of tokio. Can it run inside WasmEdge now?

Oh there're some changes in my local repo that are not pushed to the remote. Just need to change the dependency git url in `Cargo.toml`.

**Comment by richardchien** [comment]
Updates since last time:

- Moved WasmEdge Anna client to [WasmEdge/wasmedge-db-drivers](https://github.com/WasmEdge/wasmedge-db-drivers)
- Supported PUT/GET *set* values and *casual* values (previously only *last writer win* values)
- Implemented key address cache and TCP connection cache, so that consecutive requests don't need to do redundant connection and address query
- Coorperated with @MediosZ to fix a bug of [Tokio for WasmEdge](https://github.com/WasmEdge/tokio)
