### ISSUE TITLE
[Feature] Propose to provide an FVM implementation based on WasmEdge.

### ISSUE THREAD

**Issue by CaptainVincent** [WasmEdge/WasmEdge#1526]
## Motivation

Add more use cases and partnerships with our wasm engine.

## Details

The FVM is a major update to the FileCoin network. This work will enhance the WasmEdge runtime to support FileCoin specific host functions and data structures. We will also enhance the WasmEdge Rust SDK to work with FVM’s integration points. We will provide node software release packages and documentation for the operator and developer communities to deploy WasmEdge-based FVM nodes.

**Comment by CaptainVincent** [comment]
I am trying to organize a form in comparison with other engine in multiple ecosystems.
[google sheet](https://docs.google.com/spreadsheets/d/1zFAxaV1Q5F7AY1qC4Pt5PclxfVmM2B8bZLvPGhD4q3E/edit?usp=sharing)

**Comment by CaptainVincent** [comment]
Success hard code launch Wasmedge and execute pure wasm bytecode from integration test.
> pure wasm bytecode means not involve any FVM sdk's host functions as below 
- [ ] send
    - [ ] send
- [ ] vm
    - [ ] abort
    - [ ] context
- [ ] gas
    - [ ] charge
- [ ] ipld
    - [ ] block_open
    - [ ] block_create
    - [ ] block_read
    - [ ] block_stat
    - [ ] block_link
- [ ] self
    - [ ] root
    - [ ] set_root
    - [ ] current_balance
    - [ ] self_destruct
- [ ] actor
    - [ ] resolve_address
    - [ ] get_actor_code_cid
    - [ ] get_builtin_actor_type
    - [ ] get_code_cid_for_type
    - [ ] new_actor_address
    - [ ] create_actor
- [ ] debug
    - [ ] enabled
    - [ ] log
    - [ ] store_artifact
- [ ] network
    - [ ] base_fee
    - [ ] total_fil_circ_supply
- [ ] rand
    - [ ] get_chain_randomness
    - [ ] get_beacon_randomness
- [ ] crypto
    - [ ] verify_signature
    - [ ] hash
    - [ ] compute_unsealed_sector_cid
    - [ ] verify_seal
    - [ ] verify_post
    - [ ] verify_consensus_fault
    - [ ] verify_aggregate_seals
    - [ ] verify_replica_update
    - [ ] batch_verify_seals

**Comment by CaptainVincent** [comment]
Continue add Wasmedge into execute flow but catch abort signal behavior from macro. Need clarify how to handle it in the right way.

**Comment by CaptainVincent** [comment]
Finish phase 1 draft version about integrate wasmedge sdk into init, cache, execute flow.

**Comment by CaptainVincent** [comment]
Phase2 draft version.
1. Modify wasmedge-sys binding, pass  external data ptr to host functions. 
2. Breakup macro binding code to normal trait.

**Comment by CaptainVincent** [comment]
### Below is the test flow for phase 1 & 2 commits both.

- [code base](https://github.com/second-state/filecoin-wasmedge/tree/porting-wasmedge)
  - phase 1 : 8ab3e9a538e95900a0862d8e17a6f2d23f2ee31c
  - phase 2 : 13adbd7c205211b97017360189ef6a7f4dee1bfc

1. build Wasmedge first
`workspace` depend on where you clone the repo
```bash
export WORKSPACE=$HOME/workspace/_filecoin/filecoin-wasmedge
cd $WORKSPACE/WasmEdge
mkdir -p build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=OFF .. && make -j
```

2. build and run fil-hello-world-actor (integration test)
```bash
cd $WORKSPACE/ref-fvm/testing/integration/
export WASMEDGE_BUILD_DIR=$WORKSPACE/WasmEdge/build
export LD_LIBRARY_PATH=$WASMEDGE_BUILD_DIR/lib/api
cargo test hello -- --nocapture
```
### Phase 1
Put wasmedge into engine initial, execute and cache flow, but simplify it `without` binding any system host functions.
> I modify fil-hello-world-actor test case to without any host functions version.

expect result: still pass test and show below message verify wasmedge success run and return same result.
```
wasmtime results : Ok(0)
wasmedge result : Ok([WasmValue { ctx: WasmEdge_Value { Value: 0, Type: 127 }, ty: I32 }])
```

Next action items:
1. store need keep more information (invocation data) in the execution life scope.
2. binding sys host functions.

### (WIP) Phase 2
Binding host functions through Vm
> I tried to through the executor import function to follow the code flow in phase 1, but this didn't work, so I rewrote this part through Vm's interface.

1. Modify wasmedge-sys binding for pass external data pointer to host functions
> for pass invocation data
2. Breakup macro binding code to normal trait (bind.rs),
> exist some unfinished tasks here
ex. pass dummy args to host function for test (need utility function convert WasmValue into u32)

Next action items:
1. how to accept flexible return type from host function
2. fully migration the binding code in bind.rs
3. fix wasmedge execution failed with unreachable instruction, Code: 0x89

Current execution result:
```
[2022-08-09 03:36:43.130] [error] execution failed: unreachable, Code: 0x89
[2022-08-09 03:36:43.130] [error]     In instruction: unreachable (0x00) , Bytecode offset: 0x000000e4
[2022-08-09 03:36:43.130] [error]     When executing function name: "invoke"
```

**Comment by CaptainVincent** [comment]
Reorganize issue info [here](https://github.com/second-state/filecoin-wasmedge/issues/1).
And move some info as guideline put into [wiki](https://github.com/second-state/filecoin-wasmedge/wiki) page.

**Comment by hydai** [comment]
Are we going to implement this feature? Or is it fine to close?

**Comment by juntao** [comment]
Let's close it for now
