### ISSUE TITLE
LFX Workspace: Implement component-model proposal in WasmEdge

### ISSUE THREAD

**Issue by phyBrackets** [WasmEdge/WasmEdge#1536]
## Motivation

The [component-model](https://github.com/WebAssembly/component-model) proposal merges and supersedes the [Module Linking](https://github.com/WebAssembly/module-linking/) and [Interface Types](https://github.com/WebAssembly/interface-types) proposals.

With this feature, WasmEdge can execute multiple modules wasm with Module Linking and and more flexible types with Interface Type.

## Milestones

- [x] Define all new types.
- [ ] Add new instructions signature.
- [ ] Adding support for `module` section.
- [ ] Adding support for `instance` section.
- [ ] Adding Support for `alias` section.

**Comment by phyBrackets** [comment]
Here is the ongoing PR on adding Interface Types https://github.com/WasmEdge/WasmEdge/pull/1550 , currently most of the types are defined except `Unit` and `Option` will add soon them as well. For now I'm gonna start working on loader and parser side. 
Thanks

**Comment by dannypsnl** [comment]
To ensure our development range, let's fixed the tool and specification version

- Tool that coverts `.wat` to `.wasm`: `wasm-tools` [6c127a](https://github.com/bytecodealliance/wasm-tools/tree/6c127a6b2913c6be410372bd48c6710022f0c1e4)
- Specification [b9be93](https://github.com/WebAssembly/component-model/tree/b9be93e6311873ba8234e073203c9e27f2412c71)
