### ISSUE TITLE
LFX Workspace: Provide a wasm-compatible Rust TLS implementation

### ISSUE THREAD

**Issue by TieWay59** [WasmEdge/WasmEdge#1549]
## Motivation

> via: [Provide a wasm-compatible Rust TLS implementation - Issue #1430 - WasmEdge/WasmEdge (github.com)](https://github.com/WasmEdge/WasmEdge/issues/1430)

The WasmEdge networking socket API provides support for TCP and HTTP connections. But many web services today require HTTPS connections. That means we need to support TLS in WasmEdge. The [Rustls](https://github.com/rustls/rustls) crate is the most popular TLS implementation in Rust. However, Rustls is based on the Ring library, which cannot be compiled into WebAssembly.

In WasmEdge, we now [support](https://github.com/WasmEdge/WasmEdge/issues/345) the [wasi-crypto spec](https://github.com/WebAssembly/wasi-crypto). That allows us to compile the [rust-crypto](https://crates.io/crates/crypto) library into WebAssembly and run it on WasmEdge. The goal of this project is to create a Rust TLS implementation based on rust-crypto.

## Milestone

> this section might be updated in future changes.

- [x] Compare native Cpp implementation to Rust implementation.
- [ ] Abstract a set of cryptographic APIs (I hope it's RustCrypto) in Rustls
- [ ] pull request it upstream, so that upstream can use conditional compilation(provide an option like `feature = "wasi-crypto"`) to choose the encryption backend.
- [ ] Then we provide a Wasi-crypto implementation.

**Comment by TieWay59** [comment]
## Workspace Week 1

Meeting date: 2022-06-12 (Kick-off meeting with Michael Yuan)

Minute:

- Evaluate the workload of this project.
- Compare to native Cpp implementation, evaluate a better solution for this project.

According to Michael and my understanding, here below is my insight into the Cpp implementation:

- Advantages:
  - Can bypass some code implementation issues and have a mature and reliable system cryptography library available.
  - Probably more efficient (I don't agree on this point, as efficiency is related to the level of programming).
  - If the target is narrowed down to a single system, the goal can be achieved more quickly.
- Disadvantages:
  - Not good for cross-platform, if we have to do adaptations for other systems in the future, expect more work.
  - There may be pressure on your guidance side because it would mean a big change in the subject matter, and I feel sure to discuss it with you.
  - To be honest, I don't think there is necessarily less workload.

**Comment by juntao** [comment]
OK. So we will focus on Rustls instead of native-tls now. Right?

**Comment by TieWay59** [comment]
## Workspace Week 5

Feedback 1: What language option to choose: rust
I made these comparisons below.

1 from the base dependency.

With c++ I think I need to bind the libssl part of OpenSSL to WebAssembly and then rust bind it with OpenSSL to call it. However, the algorithms required by tls1.3 have been tested by rust crypto, while tls1.2 may be weak. If only tls1.3 is supported, the development process will be smoother with rust.

2 from workload.

My approach is to go through rustls project for where to use the ring and WebPKI, in fact, not as much as I thought. rustls project itself has the amount of code in about 3w lines, the ring may be about 8000 lines. If the developer wants to bind CPP's OpenSSL then the code size is estimated to be about the same, but this is completely written by itself (expected to be 10,000 lines). That is to say, the amount of CPP code I expect is beyond rusts.

3 from the debugging process.

Rust compiled into wasm directly on the webassembly test will be much easier, while the host function debug will be a lot of trouble. Developers need to dbg wasmedge to run webassemblt file, which is not easy.

Conclusion: Cpp will be more complicated, and with my last post opinion in this issue, I think rust will be a better choice.

Feedback 2: Project Design
My initial idea is shown below, but this is not my final version yet, because I can feel that this design will cause more changes to the upstream rustls, which is difficult.

![uml-1](https://user-images.githubusercontent.com/40034603/178153592-ca23a4f3-4ce3-45f0-9fbc-cd488d0b3af6.png)


I've sent an email to the maintainer of rustls to discuss this. I expect there will be considerable benefit to both communities.

I plan to complete a more detailed design next week and get feedback from the rustls community.

> Sorry for my hibernation of four weeks, It's related to my personal issues, I'll keep working harder to make up for it in the following weeks. @juntao

**Comment by juntao** [comment]
Thanks. So, we have decided NOT to use host functions, but to implement TLS using Rust and then compile it to WASM. Correct?

**Comment by TieWay59** [comment]
> Thanks. So, we have decided NOT to use host functions, but to implement TLS using Rust and then compile it to WASM. Correct?

Yes.

**Comment by TieWay59** [comment]
[see also in my traker repo](https://github.com/TieWay59/2022-LFX-Mentorship-Tracker/blob/master/weekly-blogs/week-06/week-06.md)
# week-06

## What I met

After my repeated attempts, I found that the members of rustls were not very willing or energetic to communicate about the replacement of the ring backend. Because I did not get a reply to my email, comment (see <https://github.com/rustls/rustls/issues/521>). But once I filed a small PR(see <https://github.com/rustls/rustls/pull/1085>), I soon received feedback. I think maybe I should just open up a new issue to draw their attention.

So after a discussion with Vivian, I think I would begin my work breaking changes fork without their blessing.

Here is how I think the document is structured.

```shell

project name: wasmedge-rustls (a fork of rustls)
.
├── ...                 # The project structure remains the same, but all ring and webpki calls will be replaced
├── src
│ └── ...
│─ tests
│ └── ...
│── crypto-traits/*     # Contains traits that replace the ring encryption algorithm
│── crypto-impls/*      # The implementation of the corresponding traits, in this section I will use wasi-crypto as a dependency
└── ...

```

## What problems I had

My problems at this stage are two main points.

- I'm quite unsure because I can't get advice from the official members of rustls.
- I'd like to know how to test HTTPS support, i.e. what should my Use case look like?

Specifically, what are some examples of wasmedge calls to TCP and HTTP at this stage? I've searched the rust documentation and there is no rust networking material. How should I test HTTPS support maybe WasmEdge's example of using TCP and HTTP support can help me.

## What's next

- I will just open up a new issue to draw rustls folk's attention.
- Set up my fork branch with a trying of simple trait extraction.
- Figure out how to test HTTPS in WasmEdge or how we wish it to be like.

**Comment by juntao** [comment]
Thank you for the update. I believe that we need to fork rustls first and have a complete working solution on our end first.

In terms test examples, there are a few HTTP examples in WasmEdge tokio. You can create an HTTPS GET request to a public site (eg google.com) as a test. 

https://github.com/WasmEdge/tokio/tree/wasmedge/examples

**Comment by TieWay59** [comment]
Thank you @juntao, and I want to make sure that if https://github.com/second-state/wasmedge_http_req is the current HTTP support lib. I found it in second-state org but it seems still in active development.

**Comment by TieWay59** [comment]
# week-07 & week-08

After many close discussions with @sonder-joker, I have figured out how to run  WASI-Crypto (which is also in a heated developing period) and we found out that we misunderstood each other on the design. 

There is a long story that I failed to share here. I think it's too long to display here in the issue comments, so I have uploaded my tracked details in my repo: 

- [week-07](https://github.com/TieWay59/2022-LFX-Mentorship-Tracker/blob/master/weekly-blogs/week-07/week-07.md)
- [week-08](https://github.com/TieWay59/2022-LFX-Mentorship-Tracker/blob/master/weekly-blogs/week-08/week-08.md)

**Comment by TieWay59** [comment]
# week-09 & latest progress

[week-09](https://github.com/TieWay59/2022-LFX-Mentorship-Tracker/blob/master/weekly-blogs/week-09/week-09.md)


## Discussion

Dirkjan Ochtman suggested that I refer to the integrated approach of the Quinn project.

After my discussion with my [sonder-joker](https://github.com/sonder-joker) , I got a better understanding of the project design.

First, two kinds of features should be created, a ring and a Wasi-crypto.

```INI
# in cargo.toml

[dependencies]
ring = { .. , optional = true }
wasi_crypto = { .. , optional = true }

# this is a example for demonstration
[features]
default = ["ring"]
ring=["dep:ring"]
wasi-crypto=["dep:wasi_crypto"]
```

When compiling, you can choose `cargo build --features crypto` to compile the corresponding version.

In the project code, I will replace each ring call point with the corresponding programmatic implementation, e.g.

```rust
#[cfg(feature = "ring")]
use ring::aead;

#[cfg(feature = "wasi-crypto")]
use wasi_crypto::aead; // this is an imaginary structure
```

If I implement an interface similar to Ring, I can change the original logic of the code as little as possible.

But the WASI-crypto interface is still very low-level, so I may have to wrap a module inside the project:

```text
rustls
    ├── wasi_crypto_ringified
    │   ├── aead # use wasi_crypto
    │   └── ..
    └── ..
```

```rust
#[cfg(feature = "ring")]
use ring::aead;

#[cfg(feature = "wasi-crypto")]
use crate::wasi_crypto_ringified::aead; // this is an imaginary structure
```

This makes it easy for me to manage these implementations in one place.

My current preference is to use WASI-crypto to mimic the ring interface because of two things.

1. From what I know so far WASI-crypto is called in a more low-level way.
2. It minimizes the breaking change to the source code since a lot of files will need to be changed.

## Objectives

- [x] Clone the Rustls
- [ ] Find the commonality between WASI-crypto and ring and try to design wasi_crypto_ringified that simulates ring.
  - [ ] List out the APIs that I can use directly.
- ~~ I will just open up a new issue to draw rustls folk's attention.~~
  - [ ] Share my ideas with Dirkjan. Since he replied to my email, I'll try to contact him in priority seeking more advice. Including the insights, I received above.
  - [ ] Refine my design if any new ideas come out.
- [x] Figure out how to test HTTPS in WasmEdge or how we wish it to be like. (test in WASI-crypto will be a nice example)
