### ISSUE TITLE
LFX Workspace: Support serialize and deserialize in WasmEdge

### ISSUE THREAD

**Issue by OmkarAcharekar** [WasmEdge/WasmEdge#1841]
# Motivation
WasmEdge can load the WASM binary and instantiate it into WASM module instances for execution. In a use case, we need to serialize the loaded WASM data structure back into the encoded WASM binary or deserialize the serialized one into the WASM data structure in WasmEdge. With the serializing mechanism, WasmEdge can control the WASM binary wisely such as caching or snapshotting.

# Milestones
- [x]  Study Wasm binary format, Wasm C APIs and setup working environment, 1 week.
- [x]  Design a serialize function that provides the parameter Module(type `WasmEdge_ASTModuleContext`) and returns an array of bytes, 2 ~ 5 weeks.
    * CustomSection
    * TypeSection 
    * ImportSection
    * FunctionSection
    * TableSection
    *  ElementSection 
    * MemorySection 
    * GlobalSection
    * ExportSection
    * StartSection
    * CodeSection
    * DataSection
    * DataCountSection
    * AOTSection
- [ ] Design a deserialized function that provides the parameters an array of bytes and returns a Module(type `WasmEdge_ASTModuleContext`), 1 ~ 2 weeks.
- [ ]  Add Support to remove non essential sections while serializing the module, 1 -2 weeks.

Unit tests for each task will be done during its development

# Progress

## Week 1

*  Study Wasm binary format, Wasm C APIs and setup working environment. 
*  List out the milestones to be achieved.

## Week 2

*  Understand the existing code base .
*  Implementations plans.
 
## Week 3

*  Implemented serialization & deserialization for  following sections : 
CustomSection , FunctionSection , MemorySection , ExportSection , StartSection , DataCountSection.

* Remaining  Sections : 
TypeSection , ImportSection, TableSection, ElementSection ,  CodeSection, GlobalSection , DataSection, AOTSection
 
##  Week 4

*  Experimented with Boast Serialization library.
*  Designed the external API  to expose serialize and deserialize functions 
      `WASM_API_EXTERN void wasm_module_serialize(wasm_module_t*, own wasm_byte_vec_t* out)`
      `WASM_API_EXTERN void wasm_module_deserialize(const wasm_module_t*, own wasm_byte_vec_t* out)`
*  Implemented  serialization & deserialization for DataSection and AOTSection , Partially Element Section.
* Remaining Sections :  TypeSection , ImportSection, TableSection,  CodeSection, GlobalSection.

## Current

* This week I will work on the Remaining Sections.
* Implement Tests for Serialize & Deserialize functions.

# Appendix

*  [Serialize and deserialize in Wasm C API proposal](https://github.com/WebAssembly/wasm-c-api/blob/c9d31284651b975f05ac27cee0bab1377560b87e/example/serialize.c#L54-L63)
*   [WebAssembly binary format](https://webassembly.github.io/spec/core/binary/index.html)
*  #1741

**Comment by hydai** [comment]
Please break down the serialized functions to every component, say the Module contains lots of sub-components, it should have a detailed list to ensure everything is on the list. Also, your plan doesn't include any `unit test` or `integration test`, please add them into the milstones.

**Comment by q82419** [comment]
For the sections I think you can skip currently:
* AOTSection
For the sections you can skip or just copy the buffer back when serializing:
* CustomSection
Be ware that when serialzing, the section order should not be changed (compare with the original WASM).

**Comment by q82419** [comment]
# Sample of serializing a section

You can refer to the [binary format of WASM](https://webassembly.github.io/spec/core/binary/modules.html) for details.
For every [sections](https://webassembly.github.io/spec/core/binary/modules.html#sections), the binary format is encoded as following:

```
SectionID:byte SectionSize:u32(leb128) SectionContent
```

In the data structure of loaded module in WasmEdge, the [`Section` class](https://github.com/WasmEdge/WasmEdge/blob/master/include/ast/section.h#L26) record the sections' size and the content in the derived classes.
Therefore, to serialize a section, you should output the binary of the encoded format, that is, the section binary format mentioned above.

For the special decoding of objects like `name`, `u32`, ..., etc., you can refer to the [file manager](https://github.com/WasmEdge/WasmEdge/blob/master/lib/loader/filemgr.cpp).

For the section decoding, you can refer to the [loading and constructing AST](https://github.com/WasmEdge/WasmEdge/tree/master/lib/loader/ast).

There may be several structure layers (such as `ImportSection` contains the vector of `ImportDescription`). You should follow the source tree of WasmEdge and the WASM spec to serialize them recursively.

## Custom section

The [content of custom sections](https://webassembly.github.io/spec/core/binary/modules.html#custom-section) is:

```
Name:vec(byte), Buf:vec(byte)
```

So you can try to serialize the custom section like this:

```cpp
std::vector<uint8_t> EncodeU32(const uint32_t Val) {
  // ....
  // Encode the uint32_t value into LEB128 and return the buffer.
}

std::vector<uint8_t> Serialize(const AST::CustomSection &CustomSec) {
  // First encode the section content.
  std::vector<uint8_t> Buf;

  // Name: vec(byte)
  // vec(byte): size:u32, bytes
  auto EncodedSize = EncodeU32(CustomSec.getName().length());
  Buf.insert(Buf.end(), EncodedSize.begin(), EncodedSize.end());
  Buf.insert(Buf.end(), CustomSec.getName().cbegin(), CustomSec.getName().cend());

  // Buf: vec(byte)
  // vec(byte): size:u32, bytes
  EncodedSize = EncodeU32(CustomSec.getContent().size());
  Buf.insert(Buf.end(), EncodedSize.begin(), EncodedSize.end());
  Buf.insert(Buf.end(), CustomSec.getContent().cbegin(), CustomSec.getContent().cend());

  // The section ID of custom section is 0x00.
  std::vector<uint8_t> Result;
  Result.push_back(0x00U);

  // The section size.
  EncodedSize = EncodeU32(Buf.size());
  Result.insert(Result.end(), EncodedSize.begin(), EncodedSize.end());

  // Connect the section content.
  Result.insert(Result.end(), Buf.begin(), Buf.end());

  // This is an bruteforce example. You should do it more wisely.
  return Result;
}
```

## Start section

The [content of start sections](https://webassembly.github.io/spec/core/binary/modules.html#start-section) is:

```
FuncIndex:u32(LEB128)
```

So you can try to serialize the start section like this:

```cpp
std::vector<uint8_t> EncodeU32(const uint32_t Val) {
  // ....
  // Encode the uint32_t value into LEB128 and return the buffer.
}

std::vector<uint8_t> Serialize(const AST::StartSection &StartSec) {
  // First encode the section content.
  std::vector<uint8_t> Buf;

  // FuncIndex: u32
  if (StartSec.getContent()) {
    auto EncodedSize = EncodeU32(*StartSec.getContent());
    Buf.insert(Buf.end(), EncodedSize.begin(), EncodedSize.end());
  } else {
    // If the start section doesn't have the content, it's not necessary to encode it.
    // It's the same if the content vector of other sections are empty.
    return {};
  }

  // The section ID of custom section is 0x08.
  std::vector<uint8_t> Result;
  Result.push_back(0x08U);

  // The section size.
  auto EncodedSize = EncodeU32(Buf.size());
  Result.insert(Result.end(), EncodedSize.begin(), EncodedSize.end());

  // Connect the section content.
  Result.insert(Result.end(), Buf.begin(), Buf.end());

  // This is an bruteforce example. You should do it more wisely.
  return Result;
}
```

**Comment by q82419** [comment]
For the remain time, I suggest that you should finish the following.

1. Design an code architecture to serialize the `WasmEdge::AST`, like the `WasmEdge::Loader` did to load and construct the data structure recursively.
2. The `TypeSection`, `FunctionSection`, `TableSection`, `MemorySection`, `ImportSection`, `ExportSection`, and `DatacountSection` are easier to serialize.
3. For the finished sections, you should do the unit test to verify that the serialization is correct.

**Comment by q82419** [comment]
Serialization merged and will be supported in 0.14.0.
