### ISSUE TITLE
[Java SDK] Road Map

### ISSUE THREAD

**Issue by kenvifire** [WasmEdge/WasmEdge#2025]
## Motivation

Provide Java SDK for WasmEdge

## Details

Road map
Tasks:
- [x] Set up wasmedge-jni project
- [x] Set up wasmedge-java project
- [ ] Wrap c apis
    - [ ] WasmEdge Basics
       -  [x] Version
       -  [x] Logging Settings
       -  [x] Value Types
       -  [x] Strings
       -  [x] Results
       -  [ ] Contexts
           - [x] ConfigureContext
           - [x] FunctionTypeContext
           - [x] ASTModuleContext
           - [x] ExecutorContext
           - [x] ExportTypeContext
           - [x] GlobalTypeContext
           - [x] ImportTypeCOntext
           - [x] LoaderContext
           - [x] MemoryTypeContext
           - [x] LoaderContext
           - [x] StoreContext
           - [x] StatisticsContext.
           - [x] TableTypeContext
           - [x] ValidatorContext
    - [ ] WasmEdge VM
      - [x] VM Creation
      - [ ]  Preregistrations
      - [x]  Host Module Registrations
      - [x]  Wasm Registration and Executions
      - [x] Instance Tracing
    - [ ] WasmEdge Runtime
       - [x] Loader
       - [x] Validator
       - [x] Executor
       - [x] AST Module
       - [x] Store
       - [x] Instances
       - [ ] Host Functions
     - [ ] AOT compiler
        - [x] Compiler options    
     - [x] Async API
- [ ] Documentation
   - [x] Readme, build and install instructions 
   - [ ] Java API docs
   - [ ]  Step by step examples  
 - [ ] CI workflow
    - [ ] build on different platforms
    - [ ] publish to maven repository
  - [ ]  Refactor
    - [x] Generate JNI header automatically
    - [ ] Generate JNI constants automatically
  - [ ] Bug fixes
 

## Appendix

Please feel free to add more features under this issue.

**Comment by hangedfish** [comment]
https://github.com/WasmEdge/WasmEdge/blob/067919aae2244453ab8c7caa04832ed4aeb73403/bindings/java/wasmedge-jni/CMakeLists.txt#L10

I think that Gradle could build WasmEdge library from sources, not required WasmEdge installed.

References:
* [WasmEdge-Android](https://github.com/WasmEdge/WasmEdge/tree/master/utils/android/app/lib)
* [gradle-cmake](https://github.com/tomtzook/gradle-cmake)
* [gradle-jni](https://github.com/stwind/gradle-jni)

**Comment by kenvifire** [comment]
@hangedfish Thanks for your suggestions. Added gradle jni in [this PR](https://github.com/WasmEdge/WasmEdge/pull/2055)

**Comment by alabulei1** [comment]
@kenvifire Do we have some docs for Java Host to embed WasmEdge?

**Comment by kenvifire** [comment]
> @kenvifire Do we have some docs for Java Host to embed WasmEdge?

Not yet, I haven't finished all the APIs yet and they may change in the future. I'll provide one once the APIs are stable.

**Comment by hydai** [comment]
Closing this due to #4191
