### ISSUE TITLE
LFX Workspace: streaming data processing with WasmEdge

### ISSUE THREAD

**Issue by xxchan** [WasmEdge/WasmEdge#2349]
This is the workspace of the LFX mentorship #2231 .

Code workspace https://github.com/xxchan/fluvio/pull/1

# Motivation

Fluvio is an open-source data streaming platform with in-line computation capabilities. It utilizes Wasm to support user-defined compute functions in the data stream. We would like to integrate WasmEdge as an alternative runtime for Fluvio.

# Milestones

- [x] pretest: Quick attempt to replace wasmtime with WasmEdge in `filter`
- [x] Investigate fluvio's usage of wasm engine in more detail, and design a solution to support different wasm engines at the same time in a maintainable way. (2 weeks)
  - Investigated fluvio's smartmodule wasm ABI
  - Investigated fluvio's usage of wasm engine, including moving data from/to wasm memory, usage of the wasm store.
  - https://github.com/infinyon/fluvio/pull/3122 simplified the code of smartengine transform during investigation, which will also make later work easier.
- [x] Implement full WasmEdge engine support. Pass all Fluvio integration tests. (3 weeks)
  - A trait abstraction for Wasm module is implemented.
  - WasmEdge already fully supported and all original tests passed.
  - Wasmtime implementation is also refactored to use the common code.
  - Splitting the refactoring into smaller ones to be merged in upstream:
    - https://github.com/infinyon/fluvio/pull/3152
    - ..
- [ ] Create several WasmEdge specific examples (e.g. to call an external web service if certain conditions are met, to run a Tensorflow/Pytorch AI inference) (3 weeks)
- [ ] Create docs about how to select between multiple WebAssembly runtimes. Submit PR to upstream. (1 week)
