### ISSUE TITLE
feat : Support Document AI in WasmEdge

### ISSUE THREAD

**Issue by sarrah-basta** [WasmEdge/WasmEdge#2356]
## Motivation
   The [Hugging Face](https://huggingface.co/) Hub provides a platform hosting a collection of pre-trained models, datasets, and demos of machine learning projects. This [blog](https://huggingface.co/blog/document-ai) by them gives a concise overview of the SOTA available models for Document AI, which includes many data science tasks from [Optical Character Recognition (OCR) ](https://huggingface.co/blog/document-ai#:~:text=What%20is%20Optical%20Character%20Recognition%20(OCR)%3F), [Document Image Classification](https://huggingface.co/blog/document-ai#:~:text=What%20is%20Document%20Image%20Classification%3F), [Document Layout Analysis](https://huggingface.co/blog/document-ai#:~:text=What%20is%20Document%20layout%20analysis%3F), [Document Parsing](https://huggingface.co/blog/document-ai#:~:text=What%20is%20Document%20parsing%3F) and [Document Visual Question Answering](https://huggingface.co/tasks/document-question-answering). 
    WasmEdge would like to enable easy integration of these Document AI tasks in WasmEdge applications by creating the necessary pre- and post-processing functions in Rust and using the fine-tuned models available on the [Hugging Face Model Hub](https://huggingface.co/models?sort=downloads&search=document).

## Details
Document AI tasks use [multimodal models](https://www.microsoft.com/en-us/research/lab/microsoft-research-asia/articles/revolutionizing-document-ai-with-multimodal-document-foundation-models-2/#:~:text=From%20Text%20to%20Multimodal%20Models%3A%20Document%20AI%20Gradually%20Develops%20New%20Skills), i.e models that can unify document text (using OCR) , layout (using tokens), and visual information (using spatial information from the image) in a single end-to-end framework that can learn cross-modal interactions. Each Document AI task has [a description page](https://paperswithcode.com/area/natural-language-processing) that describes its expected output and the [datasets](https://paperswithcode.com/task/document-image-classification) for the task. The corresponding [models](https://google.github.io/mediapipe/solutions/models.html) fine-tuned for these datasets are available in Pytorch format, which is supported by the Wasi-NN plugin.

This project aims to 
1. Make a set of generalized pre-processing and post-processing functions that could be used for all Document AI tasks (such as [tokenizers](https://huggingface.co/docs/transformers/main/en/main_classes/tokenizer#tokenizer) and [feature extractors](https://huggingface.co/docs/transformers/main/en/main_classes/feature_extractor#transformers.ImageFeatureExtractionMixin)) and 
2. Create inference functions for each Document AI task using the said pre- and post-processing functions and fine-tuned models from the [hub]((https://huggingface.co/models?sort=downloads&search=document)) in the backend. Each library function takes in a media object and returns the inference result. The inference function performs the following tasks.

* Takes in an input media object (e.g., a byte array for a JPEG image) and processes into a [tensor of extracted features](https://huggingface.co/docs/transformers/main/en/model_doc/layoutlmv2#transformers.LayoutLMv2ForTokenClassification.forward) (eg.  segment token indices, bounding boxes and image). 
* Use WasmEdge NN to run inference of the input tensor on the fine-tuned pytorch model.
* Collect and interpret the result tensor. Return the interpreted results in the form expected by the task (eg. a struct containing a class name for document image classification or a vector of structs containing coordinates of detected tokens for a document layout analysis task).
  
## Milestones
* [x] Create a list of models to be used along with expected inputs, outputs and necessary pre- and post-processing functions.
* [x] Import existing APIs such as the [tokenizer](https://github.com/huggingface/tokenizers/tree/main/tokenizers) library and [Tesseract OCR](https://github.com/tesseract-ocr/tesseract/blob/main/include/tesseract/capi.h) in Rust to satisfy General Pre-requisites. 
* [x] Implement necessary and common pre- and post-processing functions in Rust .
* [ ] Setup inference functions for each task using the selected model and pre-trained weights obtained from fine-tuning. 
* [ ] Create demo examples and tests for each supported document AI model and task. 
* [ ] Document, modularize code to expose relevant functions to users, and publish the library.

**Comment by sarrah-basta** [comment]
# Document AI Tasks 

## General Pre-requisites and Common Pre-processing Functions

1. OCR Engine - [Google's Tesseract](https://github.com/tesseract-ocr/tesseract)
The text from the image needs to be extracted and understood (in the form of words and bounding boxes indicating where those words occur) for all succeeding models, except for [OCR-free Document Understanding Transformer](https://arxiv.org/abs/2111.15664) like [Donut](https://huggingface.co/docs/transformers/main/en/model_doc/donut#overview). While other options exist, importing [libtesseract](https://github.com/tesseract-ocr/tesseract/blob/main/include/tesseract/capi.h), its C API into WasmEdge and calling it from Rust will be the most beneficial as further models are fine-tuned using the same engine.

2. Tokenization - [Hugging Face's Tokenizer Library](https://huggingface.co/docs/tokenizers/index)
The `words` and `bounding boxes` obtained from an OCR engine need to be passed to a tokenizer in order to [process it further](https://huggingface.co/docs/transformers/main/en/main_classes/tokenizer#tokenizer:~:text=PreTrainedTokenizerFast%20thus%20implement%20the%20main%20methods%20for%20using%20all%20the%20tokenizers). The aim is to replicate the [PreTrainedTokenizerFast](https://huggingface.co/docs/transformers/main/en/main_classes/tokenizer#transformers.PreTrainedTokenizerFast) class in Hugging Face, based on their [tokenizer library](https://github.com/huggingface/tokenizers/tree/main/tokenizers) written in Rust.

3. General Pre- and Post-Processing functions
Include all functions required to prepare input features for vision models and post process their outputs. Base on [Image Processor](https://huggingface.co/docs/transformers/main/en/main_classes/image_processor#image-processor) and [Feature Extractor](https://huggingface.co/docs/transformers/main/en/main_classes/feature_extractor#feature-extractor) in Hugging Face.

## Document AI Tasks and Model Selection

Document AI multimodal models pre-train text, layout and image in a multi-modal framework using large-scale unlabeled scanned/digital-born documents. These models are then used in visually-rich downstream document understanding tasks by fine-tuning them on the task-respective labeled benchmark dataset. The following table outlines the tasks, datasets and corresponding models to be supported in this project. 

| **DocumentAI Task** | **Benchmark Dataset** | **Required Inputs** | **Model** | **Expected Outputs** | **Reference** |
|:----:|:----:|:----:|:----:|:----:|:---:|
|Optical Character Recognition|   -   | Image |   Host function to Tesseract OCR C API  | Words, Bounding Boxes and Optional Tokenization | - |
|[Document Image Classification](https://huggingface.co/blog/document-ai#:~:text=What%20is%20Document%20Image%20Classification%3F)|[RVL-CDIP](https://huggingface.co/datasets/rvl_cdip)|1.`pixel_values` Obtained from ImageProcessor and FeatureExtractor | [microsoft/dit-base-finetuned-rvlcdip](https://huggingface.co/microsoft/dit-base-finetuned-rvlcdip#how-to-use)   |Predicted class with maximum score| [NoteBook 1](https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/image_classification.ipynb) and [Notebook 2](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/DiT/Inference_with_DiT_(Document_Image_Transformer)_for_document_image_classification.ipynb)|
|[Document Layout Analysis](https://huggingface.co/blog/document-ai#:~:text=What%20is%20Document%20layout%20analysis%3F)|[PubLayNet](https://github.com/ibm-aur-nlp/PubLayNet)|  To be tested | [nielsr/dit-document-layout-analysis](https://huggingface.co/nielsr/dit-document-layout-analysis)|Set of segmentation masks/bounding boxes, along with class names and scores|[Spaces](https://huggingface.co/spaces/nielsr/dit-document-layout-analysis) and [Python Script](https://github.com/microsoft/unilm/blob/master/dit/object_detection/inference.py)|
|[Document Parsing](https://huggingface.co/blog/document-ai#:~:text=What%20is%20Document%20parsing%3F)|[FUNSD](https://guillaumejaume.github.io/FUNSD/)|[`input_ids, token_type_ids, attention_mask, bbox, labels, image`](https://huggingface.co/docs/transformers/main/en/model_doc/layoutlmv2#transformers.LayoutLMv2ForTokenClassification.forward) Obtained from OCR Engine, [Tokenizer](https://huggingface.co/docs/transformers/main/en/model_doc/layoutlmv2#transformers.LayoutLMv2Tokenizer) and [ImageProcessor](https://huggingface.co/docs/transformers/main/en/model_doc/layoutlmv2#transformers.LayoutLMv2FeatureExtractor)| [nielsr/layoutlmv2-finetuned-funsd](https://huggingface.co/nielsr/layoutlmv2-finetuned-funsd)|A set of tokenized sequences and corresponding bounding boxes|[Notebook](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/FUNSD/True_inference_with_LayoutLMv2ForTokenClassification_%2B_Gradio_demo.ipynb)|
|[Table Detection and Extraction](https://huggingface.co/blog/document-ai#:~:text=What%20is%20Table%20detection%2C%20extraction%2C%20and%20table%20structure%20recognition%3F)|[	PubTables-1M](https://arxiv.org/abs/2110.00061)|[`pixel_values`](https://huggingface.co/docs/transformers/main/en/model_doc/table-transformer#transformers.TableTransformerModel.forward) Obtained from [ImageProcessor](https://huggingface.co/docs/transformers/main/en/model_doc/detr#transformers.DetrImageProcessor)|[https://huggingface.co/microsoft/table-transformer-detection](https://huggingface.co/microsoft/table-transformer-detection)|A struct containing bounding box and corresponding confidence for each table detected.|[Notebook](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/Table%20Transformer/Using_Table_Transformer_for_table_detection_and_table_structure_recognition.ipynb)|
|[Document Visual Question Answering](https://huggingface.co/tasks/document-question-answering)|[DocVQA](https://rrc.cvc.uab.es/?ch=17) |[`input_ids, token_type_ids, attention_mask, bbox, labels, image`](https://huggingface.co/docs/transformers/main/en/model_doc/layoutlmv2#transformers.LayoutLMv2ForTokenClassification.forward) and the `question` Obtained from OCR Engine, [Tokenizer](https://huggingface.co/docs/transformers/main/en/model_doc/layoutlmv2#transformers.LayoutLMv2Tokenizer) and [ImageProcessor](https://huggingface.co/docs/transformers/main/en/model_doc/layoutlmv2#transformers.LayoutLMv2FeatureExtractor)|[layoutlmv3-base-mpdocvqa](https://huggingface.co/rubentito/layoutlmv3-base-mpdocvqa)|A single answer to the asked question   | [Notebook](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/DocVQA/Fine_tuning_LayoutLMv2ForQuestionAnswering_on_DocVQA.ipynb) |

## Discussion Topics 

1. I have tried selecting the best SOTA models with the finetuned weights available for each task. The [LayoutLMv3](https://huggingface.co/blog/document-ai#:~:text=huggingface-,LayoutLMv3,-arxiv) based on earlier LayoutLM structures but more efficient is one such model. However. a few places warn about its [licensing issues](https://huggingface.co/blog/document-ai#:~:text=What%20are%20Licensing%20Issues%20in%20Document%20AI%3F), that I looked up in this [thread](https://github.com/microsoft/unilm/issues/352). Can anyone clarify if it would be okay to use it for this project ? 
2. In some places in the Hugging Faces Processing Functions, they provide batch support. However, since WASI-NN is only to be used for inference and not training, is it okay to skip Batch Support and just pass one object at a time to the functions ?

**Comment by sarrah-basta** [comment]
##  Week 1-2 Progress Update 

In order to achieve the first main goal of integrating Document AI, compiled a Rust Wrapper to Tesseract to WebAssembly using WasmEdge Plugins **to perform OCR on images**

- [rusty-tesseract](https://github.com/thomasgruebl/rusty-tesseract) is a rust wrapper to the command-line functionality of tesseract,hence it just uses the rust code to run the command line executable of tesseract on the host function, which can be installed with `sudo apt install tesseract-ocr` on linux.
-  Changes done to it to be able to make it compile to WebAssembly
    1. subprocess : I believe this is for execution of multiple processes, but I could not find the crate being used anywhere in the wrapper and hence safely removed it from the dependencies. 
    2. polars : This was used as a DataFrame library. However since we do not have the need for this functionality and just need the words, bounding boxes, and confidences in raw form, I removed this as well. 
    3. std::process::Command : This was necessary to run the command line functionality but I was able to replace it with the wasmedge_process_interface (https://github.com/second-state/wasmedge_process_interface) for the same functionality. 

Thus, the tesseract OCR can now be compiled to WASM from the rust code, the rough test code for which I have uploaded at https://github.com/sarrah-basta/wasmedge_ai_testing/blob/main/rusty-tesseract-wasm/README.md#build-instructions-to-build-the-wrapper .

## Week 2-3 Plan

- Understand the other main functions necessary to be able to use the `words` and `bounding boxes` given by the above OCR in a complete model and test a model that depends on tesseract working which would allow us to discover most of the potential problems we will have with other models.

**Comment by juntao** [comment]
Thank you!

**Comment by sarrah-basta** [comment]
##  Week 3 Progress Update 

In order to create the next main pre-processing block, worked on creating a tokenizer using the [Rust Tokenizers Core](https://github.com/huggingface/tokenizers/blob/main ) and compiled to WebAssembly **to tokenized text given by OCR**

- Reverse Engineered the source code to understand which which options, models and configurations of the [Core Rust library](https://github.com/huggingface/tokenizers/blob/main ) were being used by the [LayoutLMv2Processor](https://huggingface.co/docs/transformers/main/en/model_doc/layoutlmv2#transformers.LayoutLMv2Processor)
- Read through the source code of the ImageProcessor and Tokenizer classes and extracted only the relevant python code and got it working, which can be found  here :
[Python Tokenizer](https://github.com/sarrah-basta/wasmedge_ai_testing/tree/main/python_tokenizer)
-  Next, the primary psedocode was as follows :
    1. Create a "Fast" tokenizer using the Rust Core library 
    2. Encode the words obtained from OCR using the Rust function
    3. Convert the encodings obtained into a proper dictionary and then tensor format to feed to the model. 

I was able to create this [Rust Code compiled with WasmEdge](https://github.com/sarrah-basta/wasmedge_ai_testing/tree/main/tokenizer_testing) to solve the first two parts, i.e **create the correct tokenizer and obtain the encodings.**

Note : I tested this by using the words obtained via OCR from the [HuggingFaces ImageProcessor](https://huggingface.co/docs/transformers/main/en/model_doc/layoutlmv2#transformers.LayoutLMv2ImageProcessor ), this will later be replaced by wasm implementation of tesseract created earlier as well. 
I compared the tokens obtained from my Rust implementation and the HuggingFaces Python classes [here](https://www.diffchecker.com/p37Mvo6P/ ), which mostly looks correct.

## Week 4 Plan

- The next steps will be to create the end-to-end pipeline for the [Sequence Labelling/Document Parsing](https://github.com/WasmEdge/WasmEdge/issues/2356#:~:text=and%20Python%20Script-,Document%20Parsing,Notebook,-Table%20Detection%20and )task, which is what I was referring so far. This will include
    a. Integrating the rusty-tesseract-wasm OCR 
    b. Converting the obtained encodings to the correct tensor formats 
    c. Inferencing the tensors with the [PyTorch model](https://huggingface.co/nielsr/layoutlmv2-finetuned-funsd) using the Wasi-NN plugin
    
-   Once this proof of concept is complete, I will be able to
a. Clean the code and add input checks, OS checks (for running CLI tesseract commands), etc and 
b. Divide the code into modular functions.

**Comment by juntao** [comment]
Thank you so much for the update! I just want to clarify that you have created no additional host functions / plugins. You got the entire OCR program working inside WasmEdge (Rust compiled into Wasm). Is that correct? Thanks!

**Comment by sarrah-basta** [comment]
>  I just want to clarify that you have created no additional host functions / plugins
Yes @juntao , that's correct. While I originally thought this would be needed by leveraging the [C Api of tesseract](https://github.com/tesseract-ocr/tesseract/blob/main/include/tesseract/capi.h), instead, since Tesseract has a [command line functionality](https://github.com/tesseract-ocr/tesseract#running-tesseract) which can be used by simply installing the pre-built binaries, I decided to leverage that instead. 

> entire OCR program working inside WasmEdge (Rust compiled into Wasm)
Hence, yes the entire program now works inside WasmEdge, I did however have to make the **use of a plugin** : [wasmedge_process_interface](https://github.com/second-state/wasmedge_process_interface) to be able to use the  **Command Line functionality** of the native operating system (which WasmEdge is running on) while the user's Wasm is being executed on WasmEdge .

Hope this clears the need and functioning, thank you !

P.S. [Pytesseract](https://github.com/madmaze/pytesseract), the python wrapper to Tesseract, used in most AI applications I am referring, also uses an [identical](https://github.com/madmaze/pytesseract#installation) approach.

**Comment by sarrah-basta** [comment]
##  Week 4 & 5 Progress Update 

In order to create the **modular** end-to-end pipeline of the [LayoutLMv2ModelForTokenClassification](https://huggingface.co/docs/transformers/main/en/model_doc/layoutlmv2#transformers.LayoutLMv2ForTokenClassification) (currently using the temporary CLI based method for Tesseract OCR),  created the following preprocessing functions to get the inputs required by the[model](https://github.com/WasmEdge/WasmEdge/issues/2356#:~:text=and%20Python%20Script-,Document%20Parsing,-FUNSD ) in the correct Tensor formats.

- `(words, boxes) = apply_tesseract(image_name, image_width, image_height)` : applies the tesseract OCR using the wrapper to the CLI functionality of the Tesseract OCR engine and parses the output to return the Vectors of the **words** and **bounding boxes** obtained.
- `base_encodings = layoutlmv2_tokenizer(words)` : This function creates a "Fast" tokenizer using the Rust Core library and encodes the words obtained from OCR using the Rust function, making the work done in Week 3 into a modular fashion. 
- `bboxes = encoded_boxes(&base_encodings, boxes)` : This creates the bboxes in the format needed by the model, using the ids from the encodings created by the tokenizer and the boxes created by the OCR.
- `resize_image` and `to_bgr_image` :  Basic image processing functions that convert the image to a format required by the model.
- preprocessed the bboxes vector obtained by the `encoded_boxes vector`
- got inputs from encodings as `input_ids`, `attention_mask` and `token_type_ids` required by the model
- `f32_to_tensor_data` : That takes in a Vec<f32> and returns a Vec<u8> converting f32 data to u8 to create it into a tensor
-  `to_tensor` : That takes in the **tensor_data** and converts it into a `wasi_nn::Tensor`
-  converted all the above required inputs in the tensor format for the model. 

Next, I obtained the required model with the fine-tuned weights and traced it in Python to convert it to TorchScript in the function `infer_layout_lmv2` . I communicated with the mentors throughout this, and while I was able to solve most of the issues I was facing, I am still facing the following errors due to which the inference in the end-to-end pipeline is remaining. 

The code for these preprocessing functions is at https://github.com/sarrah-basta/wasmedge_ai_testing/tree/main/layoutlmv2_model .

### Errors currently facing
```bash
[2023-04-16 20:59:08.292] [error] [WASI-NN] Only F32 inputs and outputs are supported for now.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NnErrno { code: 1, name: "INVALID_ARGUMENT", message: "" }', src/main.rs:107:9
stack backtrace:
[2023-04-16 20:59:08.293] [error] execution failed: unreachable, Code: 0x89
[2023-04-16 20:59:08.293] [error]     In instruction: unreachable (0x00) , Bytecode offset: 0x001a8568
[2023-04-16 20:59:08.293] [error]     When executing function name: "_start"
```

This error is being caused due to this check in the source code [plugins/wasi-nn](https://github.com/WasmEdge/WasmEdge/blob/d2e819b0e2645386206854be2cf2585e0b6a2fb0/plugins/wasi_nn/wasinnfunc.cpp#L623-L627) however all the tensors created by me for the [inputs](https://github.com/sarrah-basta/wasmedge_ai_testing/blob/6112d57ea08f380e501d711e7f4b44eb2a7300e8/layoutlmv2_model/src/main.rs#L58-L72) are of the correct types. 
Instead, what I believe is happening is that the model ony accepts inputs in the form of `Pytorch LongTensors` which are I32, and hence F32 `FloatTensors` won't work here. I even tried various things while tracing the model, such as converting inputs to FloatTensors before tracing, and noticed the arguments `image` and `attention_mask` work in any datatype, whereas `input_ids`, `bbox` and `token_type_ids` expect **Integer values only**. 

### Possible solutions 
I am currently a little stuck and would require some guidance on how I should approach this further, is there some reason for only supporting F32 Tensors in the WASI-NN plugin for Pytorch Bckend, and if yes, is there any way to change the expectations of the TorchScript or PyTorch model ? Hopefully @juntao can give some insight.

## Week 6 Plan

- Another concern specified by @juntao was that the CLI dependency of the tesseract-ocr rust-wrapper I was using so far is not a long term viable solution, because using the command line plugin breaks the Wasm sandbox in a very unpredictable ways — the CLI program could write files or use the network without any constraints. 

Hence, I have been the C API to get identical results, and while I wait for some guidance on the above issue, I will go ahead with creating a host function with the [Rust plugin SDK ](https://github.com/second-state/wasmedge_plugin_rust_sdk) to call functions, after registering the tesseract C API as a WasmEdge plugin  (similar to https://github.com/WasmEdge/WasmEdge/blob/master/examples/plugin/get-string/getstring.cpp )

**Comment by juntao** [comment]
@apepkuss and @q82419 Can you comment on the issue about WASI NN not accepting f32 typed tensors? Thanks.

**Comment by apepkuss** [comment]
@q82419 According to the investigation by @sarrah-basta, the `wasi-nn` plugin has a type checking between [line 623 - 627](https://github.com/WasmEdge/WasmEdge/blob/d2e819b0e2645386206854be2cf2585e0b6a2fb0/plugins/wasi_nn/wasinnfunc.cpp#L623-L627). Could you please help fix the issue? Thanks a lot!

**Comment by sarrah-basta** [comment]
##  Week 8 Progress Update 

1. Created the end-to-end pipeline of the [LayoutLMv2ModelForTokenClassification](https://huggingface.co/docs/transformers/main/en/model_doc/layoutlmv2#transformers.LayoutLMv2ForTokenClassification) using the *Wasi-OCR* plugin created to obtain results from tesseract from within WasmEdge, and contains preprocessing functions to get the inputs required by the [layoutlmv2 model](https://github.com/WasmEdge/WasmEdge/issues/2356#:~:text=and%20Python%20Script-,Document%20Parsing,-FUNSD ) in the correct Tensor formats.
The code and detailed description of the working can be found at https://github.com/sarrah-basta/wasmedge_ai_testing/tree/main/layoutlmv2_with_wasi_ocr/README.md
- Dependencies and Install Instructions for the plugin
Needs WasmEdge to built with both `Wasi-OCR` and `Wasi-NN with Pytorch Backend` plugins.

2. Investigated further regarding the error being caused due to this check in the source code [plugins/wasi-nn](https://github.com/WasmEdge/WasmEdge/blob/d2e819b0e2645386206854be2cf2585e0b6a2fb0/plugins/wasi_nn/wasinnfunc.cpp#L623-L627) . 
- Made some changes to the source code, and raised an issue with a simpler reproducible code long with a working example directy in the TorchScript API at https://github.com/WasmEdge/WasmEdge/issues/2483 .
- Further details about this error and the work I have done regarding it so far can be found at this [link](https://github.com/sarrah-basta/wasmedge_ai_testing/tree/main/wasinn_testing) . 

## Week 9 Plan
- Work along with the community to solve the [issue](https://github.com/WasmEdge/WasmEdge/issues/2483) encountered in the Wasi-NN plugin.
- Creating a similar proof of concept with preprocessing functions and inference for the [DIT model](https://github.com/WasmEdge/WasmEdge/issues/2356#:~:text=microsoft/dit%2Dbase%2Dfinetuned%2Drvlcdip)

These two models and the preprocessing functions already created will be used for [4 different Document AI tasks](https://github.com/WasmEdge/WasmEdge/issues/2356#:~:text=Document%20AI%20Tasks%20and%20Model%20Selection) outlined in the first comment in this issue. Once the inferencing is (hopefully) successfully done, the last 4 weeks should be spent creating the post processing functions and packaging the code written.

**Comment by sarrah-basta** [comment]
##  Week 9 Progress Update 

1. Tested more versions and updated the community to be able to solve the [issue](https://github.com/WasmEdge/WasmEdge/issues/2483) encountered in the Wasi-NN plugin.
2. Traced the [DiT model](https://huggingface.co/docs/transformers/model_doc/dit) for [Document Image Classification](https://github.com/WasmEdge/WasmEdge/issues/2356#:~:text=microsoft/dit%2Dbase%2Dfinetuned%2Drvlcdip)
3. Added [support](https://github.com/WasmEdge/WasmEdge/blob/d2e819b0e2645386206854be2cf2585e0b6a2fb0/plugins/wasi_nn/wasinnfunc.cpp#L938) in Wasi-NN plugin for `Tuple` type output to support DiT model.
4. Tested successful inference of DiT model fine-tuned on RVL-CDIP in Wasi-NN with Dummy Inputs 
5. Created pre-processing functions for `resize_image` and `normalize_image` for DiT model. 

## Week 10 Plan
- Create an end-to-end pipeline along with post-processing functions for DiT model. 
- Put all pre and post-processing functions created till now for the Document-AI tasks in  a Rust Library Crate and create a user interface to execute each task.
