### ISSUE TITLE
LFX Workspace: Support Tensorflow and PyTorch in WasmEdge’s Python runtime

### ISSUE THREAD

**Issue by assambar** [WasmEdge/WasmEdge#2545]
# Motivation
Running Python applications in a WasmEdge container allows us to deploy super lightweight Python applications on the cloud. A Python application in a Linux container could easily take 100MB in the disk and memory space, while the WasmEdge container for Python is only 10MB.

The VMWare WasmLabs has published a pre-built Python interpreter for Wasm and had it running in WasmEdge. However, a pure Python interpreter by default does not have access to native machine learning and AI libraries. That means most machine learning applications in traditional Python would not run in the WasmEdge Python runtime.

On the other hand, WasmEdge provides support for AI frameworks through its WASI-NN extensions. WasmEdge applications can make API calls to run model inference in Tensorflow and PyTorch. We would like to support these AI framework APIs in the WasmEdge Python runtime.

# Details
In this project, you will incorporate WasmEdge’s NN (Neural Network) extensions into the Python interpreter. WasmEdge provides C and Rust APIs for guest applications to access host functions in the underlying Tensorflow and PyTorch libraries. You will make those functions accessible from the CPython-based interpreter as Python wrappers. This way, Python applications can do lightweight AI inference on the WasmEdge container.

 - Investigate and list all C-based host function APIs for Tensorflow and PyTorch inference in WasmEdge NN.
 - Create CPython wrappers for those host functions.
 - Create high-level Python wrapper functions that are ergonomic for Python developers.
 - Create CI and demo apps to validate the Python wrapper API.
 - Create detailed documentation and tutorials.
# Organizational

## General approach

 - demo-able solution at the end of each milestone - a few lines of code that anyone can copy/paste and execute in an environment with Docker, in order to run some example code, which illustrates the milestone's progress (something like [this section](https://wasmlabs.dev/articles/wasm-host-to-python/#running-it)).
 - a section of README.md describes what to do/run to execute this demo-able solution
 - it is perfectly fine if a container version for each milestone is pre-built and published on the mentee's github packages (mark as Public the first time)

## Goal

1. Implement a `wasi-nn-py` Rust crate, which offers methods that embed the CPython interpreter and adds a `wasi_nn` builtin Python module, exposing the `wasi_nn` functionality. There might also be a simple `wasi_nn.utils` module, with helper functions (e.g. `image_to_tensor`).

2. Demonstrate existing inference example in Rust and then the same, rewritten in Python. Demos shall be based on:

 - [PyTorch inference](https://wasmedge.org/docs/develop/rust/ai_inference/pytorch).
 - [TensorFlow Lite inference](https://wasmedge.org/docs/develop/rust/ai_inference/tensorflow_lite).
 - [OpenVINO inference](https://wasmedge.org/docs/develop/rust/ai_inference/openvino).

Stretch-goal: Leverage the work in [mediapipe-rs](https://github.com/WasmEdge/WasmEdge/issues/2355) to enable usage of MediaPipe from Python scripts running on Wasm.

## Milestones

- [ ] (M1) [0.5 weeks] Wasm embed Python

    - Make the [PyTorch example from the WasmEdge documentation](https://wasmedge.org/docs/develop/rust/ai_inference/pytorch) run on Eshaan's environment.
s
    - Create a command WASI module that wraps the Python interpreter (e.g. using libpython from WasmLabs + Py_Main)
    - Following the [PyTorch example](https://github.com/second-state/WasmEdge-WASINN-examples/blob/9385e2b59bf5c63ee9cff28a24e6aeb32ee491bd/pytorch-mobilenet-image/rust/src/main.rs) reuse `image_to_tensor` as it is (in Rust) and expose it to Python.
    - Define Rust wrapper and Python binding for the [`wasi_nn::load` method](https://docs.rs/wasi-nn/latest/wasi_nn/fn.load.html).
    - Demonstrate a simple Python script that loads an image from given path and transforms it to tensor. Then it loads a PT graph using the bindings that wrap `wasi_nn::load` (you will need WasmEdge with the PyTorch).

- [ ] (M2) [0.5 weeks] Container that demonstrates WasmEdge inference

    - Prepare a Dockerfile that builds a container, where we have all necessary prerequisites to easily execute the [PyTorch example from the WasmEdge documentation](https://wasmedge.org/docs/develop/rust/ai_inference/pytorch). The container should have all necessary WasmEdge plugins and 3rd party libraries.
    - Document Show a few lines of bash, which one can use to build a container image locally.
    - Document how to run the Rust PyTorch inference with the container (without having to checkout or install anything).
    - Document how to run the Python sample from M1 with the container.
    - [demo on container] Have a bash script that executes all the steps needed for demonstrating inference and then call that script.

- [ ] (M3) [2 weeks] WasmEdge+Python demonstrate PyTorch

    - Outline list of wasi-nn Rust types that are needed for the PyTorch example (all wasi_nn types and methods in Rust are here - https://docs.rs/wasi-nn/latest/wasi_nn/all.html)
    - Wrap them with Rust and expose to Python similar to what was done in M1
    - Python script that is equivalent to the full PyTorch example
    - [demo on container] Demonstrate the full PyTorch example with both Rust and Python

- [ ] (M4) [2 weeks] Full wasi-nn parity

    - Add Python bindings for all Rust types in [wasi-nn](https://docs.rs/wasi-nn/latest/wasi_nn/all.html)
    - Re-organize the Python version of those functions as necessary (e.g. in modules, choose simpler names, etc.)
    - Python scripts equivalent to the Tensorflow Lite and OpenVino examples.
    - [demo on container] Demonstrate the Tensorflow and OpenVino examples with both Rust and Python

- [ ] (M5) [1 week] Hardening

    - Add e2e tests (e.g. python scripts with models and sample images)
    - Add CI (GH actions) to validate the solution
    - [demo on container] Add code that runs those e2e tests as part of the demo

- [ ] (M6) [1 week] Usability

    - Add documentation of the solution, with diagrams and explanations
    - Create a crate that wraps libpython and offers the bindings for the `wasi_nn` python module.
    - Make the original WasmModule use this crate within a thin `main` method
    - Publish to crates.io
    - [demo on container] Add demo example of the crate, that runs `pyo3::with_gil` to run custom code from Rust, instead of py_main

- [ ] (M7) [2 week] MediaPipe

    - Explore options to Generate Python bindings for MediaPipe tasks
    - [demo on container] Python script that runs MediaPipe tasks but on WasmEdge

- [ ] (M8) [1 week] Exposure

    - Write up a blog post about this effort (target Python developers that are new to Wasm+WASI)
    - Record a video showing the docs and demonstrating the overall solution (may reuse some steps from the "demo on container") 

# Repository

This is the repository where we track the work in progress.

https://github.com/eshaanagarwal/wasi-nn-python-bindings

 - Daily commit and push is advised for historical tracking. It is OK to commit and push even with code in non-working half-done state.
 - Stable versions of the code (building end-to-end) could be tagged using a simple semantic versioning schema, e.g. `v0.1.0`, `v0.1.1`, etc.
 - Milestone versions must be tagged by `milestone-XX`.

# References

 - [feat: Support Tensorflow and PyTorch in WasmEdge’s Python runtime #2471](https://github.com/WasmEdge/WasmEdge/issues/2471)
 - WasmLabs article (+ accompanying code) on [Extending web apps with Wasm and Python](https://wasmlabs.dev/articles/wasm-host-to-python/)

**Comment by eshaanagarwal** [comment]
Week 1 update : 
1) Spent time setting up codebase. Faced some issue related to installation and I have created issue for that here #2499.
2) Went through pyo3 bindings documentation for rust.  
3) Ran and understood the example of https://github.com/assambar/rust-py-sample on my local environment. 
4) Started implementing Rust wrapper and Python binding for the [wasi_nn::load method](https://docs.rs/wasi-nn/latest/wasi_nn/fn.load.html).

**Comment by eshaanagarwal** [comment]
Update : Sorry for the delay.
Taks done : 
- Prepare a Dockerfile that builds a container, where we have all necessary prerequisites to easily execute the [PyTorch example from the WasmEdge documentation](https://wasmedge.org/docs/develop/rust/ai_inference/pytorch). The container should have all necessary WasmEdge plugins and 3rd party libraries.
- Document Show a few lines of bash, which one can use to build a container image locally.
- Document how to run the Rust PyTorch inference with the container (without having to checkout or install anything).
[demo on container] Have a bash script that executes all the steps needed for demonstrating inference and then call that script.

I have completed milestone 2. I will present all of that code and script shortly. 

Apart from that 
- Faced some issues in implenting rust wrapper and python binding for `wasi_nn::load`
- Idenitified list of wasi-nn Rust types that are needed for the PyTorch example (all wasi_nn types and methods in Rust are here  https://docs.rs/wasi-nn/latest/wasi_nn/all.html)

Work in progress : M3
- Wrap them with Rust and expose to Python similar to what was done in M1
- Python script that is equivalent to the full PyTorch example

**Comment by juntao** [comment]
I think the core of the project is to implement the Rust wrapper and Python binding for the inference functions. Can you elaborate on what problems you have encountered exactly? Thanks.

**Comment by eshaanagarwal** [comment]
Usage of GraphBuilderArray is a bit unclear. In the version 0.3.0, the following example is mentioned https://github.com/bytecodealliance/wasi-nn/tree/9e5e3a10fb13233fb13beca142157b1061486400/rust 

I was getting the folllowing error : 
```
error[E0277]: the trait bound `&[&[u8]]: PyClass` is not satisfied
  --> src/load.rs:8:39
   |
8  | pub fn load_image_graph(image_tensor: wasi_nn::GraphBuilderArray<'_>){
   |                                       ^^^^^^^ the trait `PyClass` is not implemented for `&[&[u8]]`
   |
   = note: required for `&[&[u8]]` to implement `FromPyObject<'_>`
   = note: required for `&[&[u8]]` to implement `PyFunctionArgument<'_, '_>`
note: required by a bound in `extract_argument`
  --> /home/eshaan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.1/src/impl_/extract_argument.rs:86:8
   |
86 |     T: PyFunctionArgument<'a, 'py>,
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `extract_argument`
```

**Comment by juntao** [comment]
Can you use WasmEdge examples? We cannot debug wasmtime issues. Thanks.

**Comment by eshaanagarwal** [comment]
> Can you use WasmEdge examples? We cannot debug wasmtime issues. Thanks.

Hey ! this error came as part of exposing the wasi_nn::load to python as part of M2. The wasmedge example are running as expected i believe. I had solved the issue with help of Angel and Asen's help .I will move to next tasks.

**Comment by juntao** [comment]
Hi @eshaanagarwal 

Can you provide an update on your latest progress? Thank you.

**Comment by eshaanagarwal** [comment]
Sure M1 and M2 are completed. Just need to polish the code for this. I will also share the demonstartaion video. I am currently working on M3. 

I have idenitified some of the wasi-nn Rust types that are needed for the PyTorch example and I am currently wrapping them with Rust and expose to Python similar to what was done in M1. These are the list of the rust types 

[BufferSize](https://docs.rs/wasi-nn/0.3.0/wasi_nn/type.BufferSize.html)
[Graph](https://docs.rs/wasi-nn/0.3.0/wasi_nn/type.Graph.html)
[GraphBuilder](https://docs.rs/wasi-nn/0.3.0/wasi_nn/type.GraphBuilder.html)
[GraphBuilderArray](https://docs.rs/wasi-nn/0.3.0/wasi_nn/type.GraphBuilderArray.html)
[GraphExecutionContext](https://docs.rs/wasi-nn/0.3.0/wasi_nn/type.GraphExecutionContext.html)
[TensorData](https://docs.rs/wasi-nn/0.3.0/wasi_nn/type.TensorData.html)
[TensorDimensions](https://docs.rs/wasi-nn/0.3.0/wasi_nn/type.TensorDimensions.html)

I have already done GraphBuilder Array and Also almost done with Graph and Graph Builder. I have started working on Graph Execution Context. 

If possible can we discuss the reformed deadlines or a possibility of extension for this project ?

I had to attend some medical emergencies this summer and i wish to achiev some of the relevant milestones that we had planned earlier. 

In my opinion, I think we can focus on M3 and M4 and then straight to M6 for usuability of this at priority.

**Comment by juntao** [comment]
Thank you. Can you point us to the work you have done? When you think that we will get a working demo? That is to call a Python function, which will call a Rust host and get some results back. It does not have to be a full NN demo.

**Comment by juntao** [comment]
Thanks. Do you mean 7-10 days for the M2 demo?

**Comment by eshaanagarwal** [comment]
> Thanks. Do you mean 7-10 days for the M2 demo?

Hey ! No I mean for M3. M2 is done need little polishing which I will push by tomorrow afternoon along with rest of incomplete M3 code.

**Comment by juntao** [comment]
Sounds great! Look forward to it!

**Comment by juntao** [comment]
> For a working demo, M2 will show how to load a image into tensor from Python. For the others, I expect a 7-10 days extension in which I could complete all the relavant rust types that I mentioned with demo.

@eshaanagarwal Can we have a fully working demo by the end of the month? Then, I think we can wrap up by 9/15 -- in time for KubeCon Asia at the end of the month! Please confirm whether this is okay for you!

**Comment by eshaanagarwal** [comment]
Sure this works !
