### ISSUE TITLE
LFX Workspace: Serialization Completion

### ISSUE THREAD

**Issue by dracoooooo** [WasmEdge/WasmEdge#2556]
## Motivation
Read [feat: LFX Serialization Completion](https://github.com/WasmEdge/WasmEdge/issues/2262)

WasmEdge is unable to run a WebAssembly file in text format. In order to support its execution, the existing Abstract Syntax Trees (AST) needs to be converted into binary format, which essentially involves an inverse operation of the code used to load binary format in the [lib/loader/ast](https://github.com/WasmEdge/WasmEdge/tree/master/lib/loader/ast).

When this project is complete, the existing ASTs should be able to be correctly transformed into binary format and loaded properly in WasmEdge. 

The following AST needs to be serialized: Instruction, Segment, Section, Module.

## Milestones

* [x] (M1) [1 week] Make a plan and get familiar with relevant code.
* [x] (M2) [3 weeks] Implement serialization for all instructions and add simple test cases.
* [x] (M3) [3 weeks] Implement serialization for Segment, Section, Module, and add simple test cases.
  - Note that some proposals may extend the binary format, such as [Bulk memory operations](https://github.com/WebAssembly/bulk-memory-operations/blob/master/proposals/bulk-memory-operations/Overview.md), which require special attention.
* [x] (M4) [2 weeks] Complete and detailed unit tests and integration tests.
* [x] (M5) [2 weeks] Code review and optimize the code.
* [x] (~) [1 week] Buffer for unexpected delay.

## Repository

https://github.com/dracoooooo/WasmEdge/tree/dev/serialize

## References
- [WebAssembly Binary Format](https://webassembly.github.io/spec/core/binary/index.html)
- [WebAssembly Proposals](https://github.com/WebAssembly/proposals)

**Comment by q82419** [comment]
Hi @dracoooooo ,
Welcome to raise a draft PR on your progress for discussion if you have any question.
Thanks!

**Comment by dracoooooo** [comment]
> Hi @dracoooooo , Welcome to raise a draft PR on your progress for discussion if you have any question. Thanks!

I will submit a PR this week.

**Comment by q82419** [comment]
Completed.
