### ISSUE TITLE
OSPP: Enabling WasmEdge Compilation with MSVC Toolchain

### ISSUE THREAD

**Issue by am009** [WasmEdge/WasmEdge#2629]
## Motivation

WasmEdge is a high-performance WebAssembly runtime primarily developed using the GCC and Clang toolchains. However, to broaden its reach and increase convenience for developers working on the Microsoft Windows platform, it is also essential to support the MSVC toolchain. This project aims to refactor and modify the source code to enable seamless compilation with the MSVC toolchain while maintaining its core functionality.

## Milestones

TODO add more milestone

- [ ] Fix invalid compiler argument for MSVC
- [ ] Fix compilation warnings.
- [ ] Fix #2419 
- [ ] Comprehensive documentation detailing the changes made to the source code and any potential caveats or limitations.
- [ ] Verifiy that the test suite behavior is consistent with the Clang toolchain by providing test results and comparisons.

## Related issues

- https://github.com/WasmEdge/WasmEdge/issues/2419
- https://github.com/WasmEdge/WasmEdge/issues/2423

**Comment by am009** [comment]
I got a complex template error (using MSVC). In `WasmEdge\include\experimental/span.hpp`, there are two template for `to_address`, the compiler said the usage at [`is_compatible_iterator_v`](https://github.com/am009/WasmEdge/blob/am009/20230630-template-issues/include/experimental/span.hpp#L80) is ambiguous. After spending some hours staring at the code, I still don't know how to solve it.

By the way, because a previous error (`E:\OSPP\WasmEdge\include\common/enum_errcode.hpp(79): error C7555: use of designated initializers requires at least '/std:c++20'`). I added flag `/std:c++20` in [Helper.cmake](https://github.com/am009/WasmEdge/blob/am009/20230630-template-issues/cmake/Helper.cmake#L24 ).

My code tree is at https://github.com/am009/WasmEdge/tree/am009/20230630-template-issues. The [error log](https://github.com/am009/WasmEdge/blob/am009/20230630-template-issues/2023-06-30-cxx20-to_address-ambiguous-call.out.txt#L438 ) is:
```
E:\OSPP\WasmEdge\include\experimental/span.hpp(80): error C2668: 'cxx20::to_address': ambiguous call to overloaded function
E:\OSPP\WasmEdge\include\experimental/span.hpp(42): note: could be 'auto cxx20::to_address<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>>(const T &) noexcept'
        with
        [
            _Ty=WasmEdge::RefVariant,
            T=std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<WasmEdge::RefVariant>>>
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\xutility(296): note: or       'auto std::to_address<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>>(const _Ptr &) noexcept' [found using argument-dependent lookup]
        with
        [
            _Ty=WasmEdge::RefVariant,
            _Ptr=std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<WasmEdge::RefVariant>>>
        ]
E:\OSPP\WasmEdge\include\experimental/span.hpp(80): note: while trying to match the argument list '(std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>)'
        with
        [
            _Ty=WasmEdge::RefVariant
        ]
E:\OSPP\WasmEdge\include\experimental/span.hpp(79): note: see reference to variable template 'const bool is_compatible_iterator_v<WasmEdge::Variant<WasmEdge::UnknownRef,WasmEdge::FuncRef,WasmEdge::ExternRef> const ,std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<WasmEdge::Variant<WasmEdge::UnknownRef,WasmEdge::FuncRef,WasmEdge::ExternRef> > > > >' being compiled
```

**Comment by fepicture** [comment]
the msvc indeed needs the flag to work with `designated initializers`. check with GCC and Clang works well with no explicit c++20 required. see case: https://godbolt.org/z/dKEEKqnrM code from https://abseil.io/tips/172

may try to reimpl the incompatible part(follow i suppose) `enum_errcode.hpp` to work without `designated initializers`?
https://github.com/WasmEdge/WasmEdge/blob/9a9401fc1413e895a9588533d3cf05d5f389eb4e/include/common/enum_errcode.hpp#L85-L91

if you still want to go through the `/std:c++20`, may add the namespace in the call position. say avoid the `use namespace std`
https://github.com/am009/WasmEdge/blob/am009/20230630-template-issues/include/experimental/span.hpp#L25

more reference when encounter this err in msvc:
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/18683/diffs
https://github.com/google/mediapipe/issues/1313#issuecomment-732345400

**Comment by hydai** [comment]
Hi @am009 
Currently, we would like to stay in C++17 standard. So please don't set `/std:c++20` with the MSVC toolchain. Instead, we should fix this issue by changing the implementation to avoid `designated initializers`.

**Comment by hydai** [comment]
Hi @am009 
I think we can just rewrite it with unrolling instead of figuring out a new dependency solution such as OpenMP. Hence, there will be new ipp files, so we can detect the host environment and decide to include which one in the `executor.h`

**Comment by hydai** [comment]
Hi @am009 
Do you have any progress updates or encounter any problems?

**Comment by am009** [comment]
> Hi @am009 Do you have any progress updates or encounter any problems?

I'm still working on rewriting SIMD related instructions with unrolling (solving many other errors in the meantime).
Sorry for the delay, I have been assigned many emergent tasks by my boss these days. I will update my progress by editing the milestones these days.

**Comment by am009** [comment]
Hi, I am completely back to working on this now. [This temporary commit](https://github.com/am009/WasmEdge/commit/6bbb8e5c56311b409ee3b1bcaf247e30f2451841) is my current status on this.

- Currently I am direcly modifying the code, these modifications need to be guarded by using `#ifdef` MSVC check afterwards.
- These SIMD vector type is redefined to use std::array. e.g., `using int8x16_t = std::array<int8_t, 16>;`. The reason why not choose plain array type, is related to the implementation of `ValVariant`. Using plain array type will cause some wired errors.

There are still some SIMD instructions to cover. I guess the direction is correct?

**Comment by hydai** [comment]
You can choose `std::array` for the workaround. However, I will need some time to think about it.

Another thing is that you should not change the original files. Instead, you should duplicate or split the modified parts as standalone files and use `ifdef MSVC` to include/compile the corresponding files.

**Comment by am009** [comment]
Other few things:
- Actually, I am using `#if defined(_MSC_VER) && !defined(__clang__)` to check for MSVC now. `clang-cl` will define both `_MSC_VER` and `__clang__` by default unless [`-fmsc-version=0` is set](https://stackoverflow.com/questions/67406228/clang-on-windows-how-to-disable-the-default-msvc-compatibility).
- There are a few places where we assume `__x86_64__` is not defined under MSVC. See detail [here](https://github.com/am009/WasmEdge/blob/7bbb779232ac6f0dcea01d33e5818f983bba8b31/README.md#2023-07-10-notes-on-__x86_64__)

Do I need to provide more info about related errors when using plain array as SIMD type? If I remember correctly, there are some template errors. `std::array` is fine probably because it wraps the array in a struct (I guess?). But yes, there seems no guarantee that `std::array` will not contain other members.

**Comment by hydai** [comment]
You can define a new structure for the SIMD types just like `ExternRef`.

**Comment by am009** [comment]
I'm happy to announce that I have solved all the compilation errors and test errors! Now all tests are passed! [Here](https://github.com/am009/WasmEdge/commits/am009/msvc-support) is the code branch. I think I'll start to working on compilation warnings now. 

Some fixes that worth mentioning:

- AOT compiler will generate SSE instructions, but sometimes global variables (with v128 type) is not 16-byte aligned in memory, which causes the failure of some test cases. See [this commit](https://github.com/am009/WasmEdge/commit/1688fca91805c5305fc8d633523fd15a8b282592).
  ```diff
  - ValVariant Value;
  + alignas(16) ValVariant Value;
  ```
- There is a issue in the fallback implementation of `VectorExtMul`. See https://github.com/WasmEdge/WasmEdge/pull/2736 . This issue is not specific to MSVC.
- One WASI test fails due to some flags is left uninitialized, and there are some dirty data in it. See [this commit](https://github.com/am009/WasmEdge/commit/0716e76a557765a2e9eebe5a8712ccac5bb150ae)
  ```diff
  - __wasi_fdflags_t SavedFdFlags;
  - uint8_t SavedVFSFlags;
  + __wasi_fdflags_t SavedFdFlags = {};
  + uint8_t SavedVFSFlags = {};
  ```

Some other things

- Total test time is quite long (229s), and `WasiTest.PollOneoffSocketV1` is not very stable (if you rerun it using `ctest --rerun-failed`, it will success.). I think this is related to the 100ms timeout set for the poll.
  ```
  Test project E:/OSPP/WasmEdge/build
        Start  1: wasmedgeAOTCoreTests
   1/22 Test  #1: wasmedgeAOTCoreTests .............   Passed  105.82 sec
        Start  2: wasmedgeAOTCacheTests
   2/22 Test  #2: wasmedgeAOTCacheTests ............   Passed    0.03 sec
        Start  3: wasmedgeAOTBlake3Tests
   3/22 Test  #3: wasmedgeAOTBlake3Tests ...........   Passed    0.02 sec
        Start  4: wasmedgeMixcallTests
   4/22 Test  #4: wasmedgeMixcallTests .............   Passed    0.15 sec
        Start  5: wasmedgeCommonTests
   5/22 Test  #5: wasmedgeCommonTests ..............   Passed    0.02 sec
        Start  6: wasmedgeLoaderFileMgrTests
   6/22 Test  #6: wasmedgeLoaderFileMgrTests .......   Passed    0.03 sec
        Start  7: wasmedgeLoaderASTTests
   7/22 Test  #7: wasmedgeLoaderASTTests ...........   Passed    0.03 sec
        Start  8: wasmedgeExecutorCoreTests
   8/22 Test  #8: wasmedgeExecutorCoreTests ........   Passed   21.71 sec
        Start  9: wasmedgeThreadTests
   9/22 Test  #9: wasmedgeThreadTests ..............   Passed    1.94 sec
        Start 10: wasmedgeAPIUnitTests
  10/22 Test #10: wasmedgeAPIUnitTests .............   Passed    0.41 sec
        Start 11: wasmedgeAPIVMCoreTests
  11/22 Test #11: wasmedgeAPIVMCoreTests ...........   Passed   22.11 sec
        Start 12: wasmedgeAPIStepsCoreTests
  12/22 Test #12: wasmedgeAPIStepsCoreTests ........   Passed   22.17 sec
        Start 13: wasmedgeAPIAOTCoreTests
  13/22 Test #13: wasmedgeAPIAOTCoreTests ..........   Passed   47.79 sec
        Start 14: wasmedgeExternrefTests
  14/22 Test #14: wasmedgeExternrefTests ...........   Passed    0.04 sec
        Start 15: wasiSocketTests
  15/22 Test #15: wasiSocketTests ..................   Passed    0.03 sec
        Start 16: wasiTests
  16/22 Test #16: wasiTests ........................***Failed    7.02 sec
  ... omit some output
      Start 17: wasmedgeHostMockTests
  17/22 Test #17: wasmedgeHostMockTests ............   Passed    0.03 sec
        Start 18: expectedTests
  18/22 Test #18: expectedTests ....................   Passed    0.03 sec
        Start 19: spanTests
  19/22 Test #19: spanTests ........................   Passed    0.02 sec
        Start 20: poTests
  20/22 Test #20: poTests ..........................   Passed    0.02 sec
        Start 21: wasmedgeMemLimitTests
  21/22 Test #21: wasmedgeMemLimitTests ............   Passed    0.02 sec
        Start 22: wasmedgeErrinfoTests
  22/22 Test #22: wasmedgeErrinfoTests .............   Passed    0.02 sec
  
  95% tests passed, 1 tests failed out of 22
  
  Total Test time (real) = 229.50 sec
  ```
- The `SIMDArray` type is still defined to std::array See [this commit](https://github.com/am009/WasmEdge/commit/fe23292f6a2271c82e23422a9046f28cf1bbf1e5). Do I need to switch to our own type? (we only used the overload operator `[]`, so it's not hard to implement (within a few lines I guess).)
  ```
  template <typename Ty, size_t TotalSize = 16, std::enable_if_t<(TotalSize % sizeof(Ty) == 0), int> = 0>
  using SIMDArray = std::array<Ty, (TotalSize / sizeof(Ty))>;
  ```

**Comment by hydai** [comment]
Thanks @am009 
That's great progress. Could you also create a workflow using MSVC to compile and test the WasmEdge after you clean up all warnings?

**Comment by am009** [comment]
I discovered that it is really easy to craft a workflow for MSVC, just copy the old workflow and remove the two lines that set compiler to `clang-cl`, and it's done. ([commit](https://github.com/am009/WasmEdge/commit/3bd0cac56b294977923019912991ec098aa3a58f))

Now the compiler warnings are fixed and other bugs and warnings that get discovered after running the workflow are also fixed. I fixed them by git's interactive rebase to preserve a (relatively) clean history. The code tree is at https://github.com/am009/WasmEdge/tree/am009/msvc-support

What should I do next? I guess I should write some docs? By the way, the build process using MSVC is also shockingly similar to that of clang-cl. Just remove the `CC` and `CXX` environment variables. (Or additionally add something like `-vcvars_ver=14.36.32532` to powershell command `Enter-VsDevShell`) Besides, probably there will be many other code changes during the process of code review.

**Comment by hydai** [comment]
Hi @am009 
Yes. Please write a building steps guide in the wasmedge/docs repository. If you are ready, please let me know if you need the code review for the PR.

**Comment by am009** [comment]
I think it's time to move forward to code review to further improve the patch. 
Do I need to open PR? I opened two PR:
- wasmedge: https://github.com/WasmEdge/WasmEdge/pull/2751
- doc: https://github.com/WasmEdge/docs/pull/156
I didn't add too much to the doc, because the build process of using Clang-cl and MSVC is quite similar. Is there anything else that I can add to the doc?
