### ISSUE TITLE
LFX Workspace: FFMpeg Plugin for WasmEdge along with Rust SDK

### ISSUE THREAD

**Issue by Hrushi20** [WasmEdge/WasmEdge#2769]
## Motivation

FFmpeg is widely used in machine learning for audio, video, and image processing. It is an open-source software library used to decode, encode, transcode, mux, demux, stream, filter, and play multimedia files. This makes it a powerful tool for preprocessing and manipulating media data for machine learning applications.

To utilise Ffmpeg Functionalities, pervious approach compiles FFmpeg C plugin to Wasm. The Wasm-compiled FFmpeg functions are slow compared to native performance. Therefore current strategy involves integrating FFmpeg plugin support into WasmEdge by taking advantage of WasmEdge plugins. This enables WasmEdge to interact with host environment by providing native host functions improving performance significantly. 

Ffmpeg contains multiple libraries-
* avcodec
* avfilter
* avformat
* avdevice
* avutil
* swscale
* swresample

## Goals- 
* To support the above Ffmpeg libraries in WasmEdge Plugin.
* Provide a Rust SDK for Wasm programs to access ffmpeg functions. 
* Refactor mediapipe-rs project to use ffmpeg plugin. 

## Rust SDK Design-
* The WasmEdgeFFmpeg rust crate will have a similar to [ffmpeg-rs](https://github.com/nullsauce/ffmpeg-rs)

## Milestones-
- [x] [Week 1 - 2] (Sept 4 - Sept 17)
    * Add Simple FFMpeg functions used by [mediapipe-rs](https://github.com/WasmEdge/mediapipe-rs) crate into plugin.
    * Design the system and find best practices to follow.

- [x] [Week 3] (Sept 18 - Sept 24)
    * Integrate swscale library
 
- [x] [Week 4 - 5] (Sept 25 - Oct 8)
    * Integrate avcodec library
   
- [x] [Week 6] (Oct 9 - Oct 15)
    * Integrate swresample library

- [x] [Week 7-8] (Oct 16 - Oct 29)
    * Integrate avutil library
    
- [x] [Week 9] (Oct 30 - Nov 5)
    * Integrate avformat library
   
- [x] [Week 10] (Nov 6 - Nov 12)
    * Integrate avfilter library

- [ ] [Week 11] (Nov 13 - Nov 19)
    * Write docs and tutorials. 
    
- [x] [Week 12] (Nov 20 - Nov 30)
    * Project polishing and hardening, Spare time

## Appendix
[FFMpeg Plugin for WasmEdge](https://github.com/WasmEdge/WasmEdge/issues/2689)

## Repository
https://github.com/Hrushi20/WasmEdge/tree/feature-ffmpeg-plugin
https://github.com/Hrushi20/rust-ffmpeg

**Comment by Hrushi20** [comment]
Hey @hydai, I'm working on the design on FFMpeg plugin on C++ side. I noticed that plugins maintain a internal data structure to hold Structs in c++ [Eg](https://github.com/WasmEdge/WasmEdge/blob/f6d99c87fef0db160d17ccf3f7f3cd87cbd56e68/plugins/wasmedge_tensorflow/tensorflow_env.h#L124) and store the index of the data structure in Rust side [Eg](https://github.com/WasmEdge/WasmEdge/blob/f6d99c87fef0db160d17ccf3f7f3cd87cbd56e68/plugins/wasmedge_tensorflowlite/tensorflowlite_func.cpp#L107).
 
FFMpeg, deals with a lot of structs (more than 50 structs). Do you think its apt to create an ` unordered_map <uint32_t ,void *> hashMap ` and using this to store all the structs in the plugin??? Do you have any other suggestions?

**Comment by juntao** [comment]
Thanks @Hrushi20 Please also note how you want to design the Rust SDK for the ffmpeg plugin.

**Comment by Hrushi20** [comment]
I've decided to clone the rust-ffmpeg repo and update it to support our plugin.

**Comment by juntao** [comment]
> I've decided to clone the rust-ffmpeg repo and update it to support our plugin. 

Ok. Please make sure that you credit the original authors. Thanks!

**Comment by Hrushi20** [comment]
Week 1 Update-

* Initialized the project with appropriate project structure for WasmEdge FFmpeg Plugin. For the Rust Sdk, decided to update the existing [rust-ffmpeg](https://github.com/zmwangx/rust-ffmpeg) crate.  
* Implemented an allocator to store and delete FFmpeg Structs in WasmEdge Plugin.
* Working on supporting mediapipe-rs functions using Rust-SDK. Currently ported [these](https://github.com/WasmEdge/mediapipe-rs/blob/7eee0492804661ccd76ba1da75c693f88c0ecc85/src/preprocess/common/ffmpeg_input.rs#L23-L40) functions. The functions can working via the rust sdk. Below are the sample outputs of these functions. 

<img width="1047" alt="Screenshot 2023-09-13 at 12 23 16 PM" src="https://github.com/WasmEdge/WasmEdge/assets/65367566/a2fb8e86-0afc-4f99-ac00-ca551925f306">


* Constant Refactoring and maintaining code. 
* Overall ported over 40 ffmpeg functions.

**Comment by Hrushi20** [comment]
## Week 2/3 Update -
* FFmpeg Functions required by Mediapipe-rs is added to Plugin and Rust SDK. 
* Added build.rs file in Rust SDK. This compiles `.wit` files and generates required Rust files. Users can integrate and use the Rust SDK FFmpeg library (Still under development). 
* Added Bindings for ChannelLayout, Sample Format for Audio processing in Plugin.
* Using Few Deprecated Functions in FFmpeg for higher Compatibility
   Example: channel_layout is deprecated in Version 6, however for backwards compatibility using few deprecated functions. Aim is to support V5 and V6 versions. 
* Support for Scaling library in FFmpeg Plugin is almost done. 
* Initialized the tests in FFmpeg C++ Plugin. Will be working on added tests to Mediapipe-rs based FFmpeg functions in the following weeks. 

## Challenges-
* Libc is returning a different error message for a particular error code in wasm compared to native execution.
* Need to fix what Error Code to return due to Null Pointer Issues, Invalid Type Conversion, Null value in Plugin.

**Comment by Hrushi20** [comment]
Week 4/5 Update -
* Integrated entire Scaling library along with Unit Tests (C++ Plugin).
* Integrated SWResample libraray along with Unit Tests (C++ Plugin).
* WasmEdge Rust SDK supports mediapipe-rs Sdk FFpmeg APIs. Need to integrate into mediapipe-rs.
* Added AVDictionary Functionalities. 
* Created a bash script to install FFmpeg as Dependency (While building Pipeline).
* Raised a Draft PR #2885 .

**Comment by Hrushi20** [comment]
Week 6/7 Update -
* Mediapipe-rs can now be integrated using WasmEdge FFmpeg plugin. Need to add benchmarks of previous and current approach. 
* Integrated AVFormat library along with Unit tests (C++ Plugin).
* Added AVUtil bindings.
* Added AVUtil functionalities, need to add unit tests.

* Need to refactor the C++ tests  by breaking them into simpler components.

**Comment by hydai** [comment]
Completed. Closing it.
