### ISSUE TITLE
LFX Mentorship (Sept-Nov, 2023): CNCF - WasmEdge: Support AOT mode in proxy-wasm

### ISSUE THREAD

**Issue by Shivkant-Chauhan** [WasmEdge/WasmEdge#2810]
## Motivation
WasmEdge is a WebAssembly runtime that supports both interpreter and ahead-of-time modes. For proxy-wasm support, WasmEdge only provides the interpreter mode currently. Such as the other runtimes, WasmEdge should be able to support the AOT mode for better performance. We should have the AOT mode enabled in proxy-wasm.

## Goals

- Modify the Bazel file to include the LLVM dependency.
- Modify the code to support running WASM in AOT mode.
- Add the documentation of proxy-wasm in the WasmEdge docs repo.

## Implementation Plan (after 14th Sept - Welcome meet by mentor @q82419)

- [ ] Week 1-2 : Getting familiar with the proxy-wasm-cpp-host, and the other webassembly runtimes for Wasmedge.
- [ ] Week 3-5: Experimenting with Bazel config files, documenting the implementation approaches, and get it approved by the @q82419 
- [ ] Week 6-9: Implementing the AOT support for proxy-wasm-cpp-host, with the required changes in the Bazel files for adding the LLVM dependencies.
- [ ] Week 10: Adding the documentation for the proxy-wasm in WasmEdge repo.

**Comment by Shivkant-Chauhan** [comment]
@q82419 Please take a look. Also, it seems that I don't have the rights to add label, can you please add label of `LFX mentorship`

**Comment by q82419** [comment]
Looks great. Please go ahead.
