### ISSUE TITLE
WASI preview2 proposals tracking issue

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#2939]
### Summary

This issue replaced #2806.

This issue will be marked as finished once all preview2 proposals are implemented and verified.

WasmEdge would love to have native support for the WASI preview2, including the following WASI proposals:

- [ ] [WASI-IO, including WASI-POLL](https://github.com/WebAssembly/wasi-io)
- [ ] [WASI-SOCKETS](https://github.com/WebAssembly/wasi-sockets)
- [ ] [WASI-CLOCK](https://github.com/WebAssembly/wasi-clocks)
- [ ] [WASI-HTTP](https://github.com/WebAssembly/wasi-http)
- [ ] [WASI-RANDOM](https://github.com/WebAssembly/wasi-random)
- [ ] [WASI-FILESYSTEM](https://github.com/WebAssembly/wasi-filesystem)
- [x] [WASI-NN](https://github.com/WebAssembly/wasi-nn)

### Details

To ensure we can ship the preview2 proposals smoothly and are not blocked by the current plugin limitation, we will merge all proposals, except for WASI-NN, into WasmEdge Core.

The following information will be replaced by [a GitHub Project Board](https://github.com/orgs/WasmEdge/projects/6)

## WASI-IO
Status: In Progress
Assignee: @dannypsnl 
PR: https://github.com/WasmEdge/WasmEdge/pull/2934

## WASI-Sockets
Status: In Progress
Assignee: @ LFsWang 
PR: TBD

## WASI-CLOCK
Status: In Progress
Assignee: @dannypsnl 
PR: https://github.com/WasmEdge/WasmEdge/pull/2766

## WASI-HTTP
Status: Todo
Assignee:  TBD
PR: TBD

## WASI-RANDOM
Status: In Reviewing
Assignee: @LFsWang
PR: https://github.com/WasmEdge/WasmEdge/pull/2875

## WASI-FILESYSTEM
Status: Todo.
Assignee: TBD
PR: TBD

## WASI-NN
Status: Done.
Assignee: @dm4, @hydai 

### Appendix

https://github.com/orgs/bytecodealliance/projects/10/views/1
https://github.com/WebAssembly/WASI/blob/main/Proposals.md
https://github.com/bytecodealliance/wasmtime/tree/main/crates/wasi/src/preview2

**Comment by dannypsnl** [comment]
NOTE: @hydai's idea that we can use external symbols to exchange data across plugin, instead of internalize everything.

**Comment by dannypsnl** [comment]
Another board: https://github.com/orgs/bytecodealliance/projects/10/views/1?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=Status

**Comment by dannypsnl** [comment]
In `wasi:cli` has `get-stdin: func() -> input-stream` such function, the `input-stream` is came from `wasi:io`. There are two things need to be figured out

1. Should this `input-stream` be an integer, or include header from `wasi-io`?
2. How to new a `input-stream`, or more generally, how to new a resource from plugin?

**Comment by tushar1977** [comment]
Hi @hydai , can i help in wasi-filesystem?
