### ISSUE TITLE
feat: Prepare to deprecate manylinux2014 and use a new base OS for the general Linux release process

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#3003]
### Summary

CentOS 7 will reach EOL on June 30, 2024[[1]]. Hence, we must move to a new base OS (`manylinux_2_28`) for the general Linux release process. There is no reason to maintain an outdated operating system support. There will be several action items we have to achieve. Check the `Details` section.

[1]: https://www.redhat.com/en/topics/linux/centos-linux-eol

### Details

Action items:

- [x] Create a new docker image as the successor of `manylinux2014`. #3188 
- [x] Make sure all build and release workflow are up to date. #3511 /cc @0yi0
- [x] Update the installer once `manylinux_2_28` is online. #3848 /cc @SAtacker
- [x] ~~Keep releasing with `manylinux2014` and `manylinux_2_28` until June 30, 2024~~
- [x] Deprecate the `manylinux2014` and related assets/workflows #3777

If you have any questions, please feel free to leave comments below.

### Appendix

Deprecation notice: #3154

**Comment by q82419** [comment]
Related to #3542.

**Comment by 0yi0** [comment]
Closing as #3848 has updated `installer_v2.sh`.
