### ISSUE TITLE
GSoC Workspace: Implementing Coredump for Post-Mortem Debugging in WebAssembly

### ISSUE THREAD

**Issue by sid-008** [WasmEdge/WasmEdge#3435]
# Summary

This project aims to implement wasm-coredump, to enhance the debugging capabilities of WebAssembly by implementing a coredump feature for post-mortem analysis for the wasmedge runtime. When WebAssembly encounters a runtime error, it will start unwinding and initiate a process to collect debugging information, including stack frames, local variable values, and a snapshot of the linear memory. For each stack frame, it will collect the values in locals (includes function parameters) and on the stack. Along with binary offsets to resolve to source file locations. This data is saved in a coredump file, which can be analysed post-mortem to debug the error using tools like wasmgdb.

# Basic Idea
When WebAssembly enters a trap, it starts unwinding and collects debugging information. For each stack frame, collect the values in locals (includes function parameters) and on the stack. Along with binary offsets to resolve to source file locations. Finally, make a snapshot of the linear memory (or multiple linear memories when the [multi-memory](https://github.com/WebAssembly/multi-memory) feature is used), tables and globals.

All this information is saved to the file, called the coredump file.

The post mortem analysis is done using the coredump and [DWARF](https://yurydelendik.github.io/webassembly-dwarf) information. Similar to the debugging flow with [gdb](https://linux.die.net/man/1/gdb).

# Milestones

### Community bonding period [1st May, 2024 to 27th May 2024]
- [x] Setup the working environment and build WasmEdge locally.
- [x] Understand the existing code base and requirements.
- [x] List out further future milestones if required. 

### Coding Period [27th May 2024 to 26th August 2024] 
- [x]  Define new CLI flags to enable coredump file generation, i.e being able to run a WASM module in debug mode. Read more about the coredump spec and about the various custom sections, memory sections, data sections in WASM .
- [x] Modify the section of WasmEdge code that traps execution in case of abnormal behaviour/errors to support coredump file generation(which is just a dummy file for now) and understanding how coredump runtime code was injected into the WASM module(referencing this: [wasm-edit](https://github.com/xtuc/wasm-coredump/tree/main/bin/rewriter)). This is an intermediate goal to better understand how the information would be logged and how the coredump file would be generated.
- [x] Write the module for coredump file generation, the coredump spec is straightforward and concise in defining what information is to be collected in the coredump file. The coredump file is to be encoded using the [Wasm binary format](https://webassembly.github.io/spec/core/binary/index.html)
- [ ] Implementing support for collecting information about processes and module information as defined in: [Process information](https://github.com/WebAssembly/tool-conventions/blob/main/Coredump.md#process-information) and in [instance information](https://github.com/WebAssembly/tool-conventions/blob/main/Coredump.md#module-information), we will collect information from their relevant custom sections
- [ ] Implementing support for collecting debug info on threads and stack frames, as defined [here](https://github.com/WebAssembly/tool-conventions/blob/main/Coredump.md#threads-and-stack-frames). Here as well, we will collect information from their relevant custom sections.
- [ ] Adding support for linear memory screenshotting. As defined [here](https://github.com/WebAssembly/tool-conventions/blob/main/Coredump.md#memory). We shall collect information from the memory section and data section here
- [ ] Adding support for capturing Globals from the global section as defined in the spec [here](https://github.com/WebAssembly/tool-conventions/blob/main/Coredump.md#globals).
- [ ] Making any changes if required to ensure that the coredump file is compatible with the current toolchain, including wasmgdb and wasm-edit.
- [ ] Writing tutorials, examples, and demonstrations of post-mortem debugging using the implemented coredump feature.

### Appendix

- [WASM Coredump spec](https://github.com/WebAssembly/tool-conventions/blob/main/Coredump.md)
- [Custom Sections Documentation](https://webassembly.github.io/spec/core/binary/modules.html#binary-customsec)

**Comment by hydai** [comment]
Hi @sid-008 
Do you have any updates on this issue? Please update us on the progress every week to meet the policy. Thanks!

**Comment by sid-008** [comment]
> Hi @sid-008 
> Do you have any updates on this issue? Please update us on the progress every week to meet the policy. Thanks!

Hey Hydai,

Sure, I will do the needful shortly on the github issue.

**Comment by sid-008** [comment]
# Community Bonding Period [20th May, 2022 to June 12th, 2022] - status update
- LLVM coding style has to be followed - [.clang-format](https://github.com/WasmEdge/WasmEdge/blob/master/.clang-format) and [.clang-tidy](https://github.com/WasmEdge/WasmEdge/blob/master/.clang-tidy)
- Implementations of coredump in other runtimes has been done using the `wasm-coredump-builder` rust crate.
- The coredump file itself must be encoded using the Wasm encoding format.
- End result should be a flag that enables generation of a coredump file that can be debugged using tools such as `wasmgdb`

**Comment by sid-008** [comment]
# Preliminary Analysis of existing Implementations of coredump generation and related tooling
- wasmgdb seems to have a future dependency issue with the use of its wasmparser module.
`warning: the following packages contain code that will be rejected by a future version of Rust: wasmparser v0.57.0`
- Current implementations rely on the `wasm-coredump-builder` and the [wasm-coredump-rewriter](https://github.com/xtuc/wasm-coredump/tree/main) 
- What coredump-builder is doing relies on the `polyfilling` technique this kind of approach may not be suitable for the project due to its reliance on external dependencies including a implementation to rewrite Wasm binaries that has been [written in AssemblyScript](https://github.com/xtuc/wasm-coredump/blob/main/lib/asc-coredump/assembly/coredump.ts) (see: [blog on Wasm Coredump rewriter](https://blog.cloudflare.com/wasm-coredumps))
- As per prior discussions as well; we would like to have a standalone implementation for coredump to enhance the robustness of this feature.
- The binary is essentially rewritten to support calls to an external library(I think) by calls such as:
` call $coredump/write_coredump `

### Proposed approach:
- My current approach would be to take information from lib/executor/instantiate and try to construct the coredump file from an instantiated wasm binary.

**Comment by sid-008** [comment]
# Current Status
- WasmEdge can encounter traps under various conditions(See: [Wasm Security model, Traps](https://webassembly.org/docs/security/). 
- One instruction in particular traps execution unconditionally. This is the [unreachable](https://webassembly.github.io/spec/core/exec/instructions.html#xref-syntax-instructions-syntax-instr-control-mathsf-unreachable) instruction.
- Current discussed approach is to implement the coredump pipeline for the `unreachable` instruction and then use that pipeline for other cases.
- The execution flow for the `unreachable` instruction to be encountered has been identified, a seperate coredump class has been created to collect relevant information and write out the coredump file.
- There are 6 distinct custom sections. Information for each can be fetched from the executor.

**Comment by hydai** [comment]
Hi @sid-008 
It's been a month since the last status update. What's the current progress? Do you need any assistance?

**Comment by sid-008** [comment]
> Hi @sid-008 
> It's been a month since the last status update. What's the current progress? Do you need any assistance?

Hey hydai sure, I'll post an update shortly.
