### ISSUE TITLE
OSPP Workspace: Support llm.c as a WasmEdge plugin

### ISSUE THREAD

**Issue by junaire** [WasmEdge/WasmEdge#3523]
### Summary

# Motivation

The WasmEdge Runtime is poised to offer robust inference support for AI models and Large
Language Models (LLMs) such as llama3 and phi-3-mini. Recognizing the critical importance
of training new models, we believe that leveraging WebAssembly (Wasm) can effectively
handle both inference and training tasks. Our objective is to build a WasmEdge plugin using
llm.c as the backend and to develop a set of WASI extensions (such as WASI-NN) for
developers.

# Deliverables
* A new WasmEdge plugin can be used for training GPT2.
* A Rust SDK of the WasmEdge plugin, allowing developers to create related
applications using Rust.
* Enhancement to llm.c, that makes it more modular and easier to integrate in
downstream projects.

# Milestones
- [x] (M1) [2 weeks] Initial PR for the WasmLLM plugin
* Create a PR, add a new WasmEdge plugin, and temporarily return an error when the host function is called.
- [x] (M2) [2 weeks] Fork llm.c, tweak the build system and code
* Tweak the build system of llm.c, make it possible to build it as a library.
* Refactor llm.c, move the training logic into a separate function, and export it to downstream users. Also, make necessary parameters configurable.
- [x] (M3) [1 week] Integrate llm.c into WasmEdge
* Integrate llm.c and all its dependencies into WasmEdge build systems using cmake.
- [x] (M4) [2 weeks] Implement the host functions
* Implement all host functions we defined, and write tests.
- [x] (M5) [2 weeks] Develop the Rust binding
* Develop the Rust binding, write tests, add documentation.
- [x] (M6) [2 week] Support Training GPT2 on GPU

# References
* https://summer-ospp.ac.cn/org/prodetail/248830516
* #3368 

CC @hydai

**Comment by junaire** [comment]
I have created a llm.c fork in https://github.com/junaire/llm.c/tree/jun/wasmedge to support our plugin, maybe you can take a look so we can discuss the design @hydai

**Comment by hydai** [comment]
I create wasmedge/llm.c via forking the upstream. You can submit your PR there: https://github.com/WasmEdge/llm.c

**Comment by junaire** [comment]
> I create wasmedge/llm.c via forking the upstream. You can submit your PR there: https://github.com/WasmEdge/llm.c

[PR](https://github.com/WasmEdge/llm.c/pull/1) submitted, I feel like there are a lot of things that we should discuss.

**Comment by hydai** [comment]
Hi @junaire 
You can book a slot during the office hour.

**Comment by junaire** [comment]
> Hi @junaire You can book a slot during the office hour.

hi, sry for the late response, i was very busy with my other projects recently. im not sure if we can schedule a meeting or something like that, for now maybe async communication is good enough for us. btw i left a comment in the above pr, can you plz have a look? :)

**Comment by hydai** [comment]
Sure thing. Let's do it async.

**Comment by junaire** [comment]
i would like to work on the rust binding next, but where should we put that? do we need to create a new repo? @hydai

**Comment by hydai** [comment]
We will have a new repo called wasmedge-llmc for this. But it will need some time to set it up.

**Comment by hydai** [comment]
@junaire 
The repo is created: https://github.com/WasmEdge/wasmedge-llmc

**Comment by junaire** [comment]
> @junaire The repo is created: https://github.com/WasmEdge/wasmedge-llmc

Draft PR is submitted: https://github.com/WasmEdge/wasmedge-llmc/pull/1

**Comment by hydai** [comment]
Hi @junaire 
We have to rename the namespace of your plugin from `wasi-llm` to `wasmedge-llmc`.
The reason is that all of the `wasi-` prefixes should be reversed for the WASI proposals in case of conflicts.
We are going to rename all affected plugins.

**Comment by junaire** [comment]
hi @hydai, do you want me to work on the GPU training for the plugin? I have done some research on llmc's CUDA code, and it feels like it's more efficient, complex, and complete than the CPU one. the code still lack abstractions, and the interface also changes a bit. how should we handle it? should i create another plugin like `wasmedge_llmc_cuda`?

**Comment by hydai** [comment]
> hi @hydai, do you want me to work on the GPU training for the plugin?
Definitely. If you are able to work on GPU, that would be great.

> how should we handle it? should i create another plugin like `wasmedge_llmc_cuda`?

Is it not possible to co-locate in the same plugin? The reason is that we can control the hardware backends during the configuration, such as the llama.cpp, whisper.cpp, and stable-diffusion.cpp targets. I am not sure if the llm.c can do the same thing or not.

**Comment by junaire** [comment]
> > hi @hydai, do you want me to work on the GPU training for the plugin?
> > Definitely. If you are able to work on GPU, that would be great.
> 
> > how should we handle it? should i create another plugin like `wasmedge_llmc_cuda`?
> 
> Is it not possible to co-locate in the same plugin? The reason is that we can control the hardware backends during the configuration, such as the llama.cpp, whisper.cpp, and stable-diffusion.cpp targets. I am not sure if the llm.c can do the same thing or not.

well, we can have a macro like `LLMC_BACKEND={CUDA, CPU}` so they can live in the same plugin, it's just the user can't control it in the runtime. so at the end of the day, you still need to ship 2 plugins. also, what about the rust side?

**Comment by hydai** [comment]
There should be nothing to do on the rust side. The API should be the same.
Users can decide which plugin version they really want to use, but the developers don't need to do anything on the application side.

**Comment by junaire** [comment]
Is there anything else you'd like me to deliver on this project? if not i would suggest to close the issue and mark the project as done :)

**Comment by hydai** [comment]
Sure. Let's close this issue. Thanks for your contribution :-).
