### ISSUE TITLE
OSPP Workspace: Add stable diffusion.cpp plugin for WasmEdge

### ISSUE THREAD

**Issue by Tenderyi** [WasmEdge/WasmEdge#3529]
### Summary

# Motivation

WasmEdge runtime provides inference support for AI models and LLMs (large language models, such as llama3 and phi-3-mini). Stable Diffusion is a popular category that we would like to support. We would like to build a WasmEdge plugin that uses [stable-diffusion.cpp](https://github.com/leejet/stable-diffusion.cpp) as the backend and a set of WASI extensions like WASI-NN for developers to use.

# Deliverables

Upon successful completion of this project, the following deliverables are expected:

- A Rust language framework for WasmEdge applications to support txt2img, img2img, and most of the options listed in [this table](https://github.com/leejet/stable-diffusion.cpp?tab=readme-ov-file#run)

- A WasmEdge plugin that implements and integrates the stable diffusion features.

- Documentation and sample applications

# Milestones

- [x] (M1) [2 weeks] Data collation
- Download and run the sample program of stable-diffusion, read the code and understand its implementation and calling method.
- Read PR [#3444 ](https://github.com/WasmEdge/WasmEdge/pull/3444), Understand the modified parts, implemented interfaces and functions, and how to import stable diffusion.cpp

- [x] (M2) [2 week] Parameter support
- Configure the compilation environment, reproduce the results in the [SDK and example]( https://github.com/grorge123/wasmedge-stable-diffusion), and understand the interface and implementation defined in its Rust documentation
- According to the interface defined in the [#3405](https://github.com/WasmEdge/WasmEdge/issues/3405), build my own repository, modify its Rust document, and support some parameters.

- [x] (M3) [2 weeks] Implement the rest host function
- Implement rest host function and write tests.
- Some things need to be improved:
  - Resize the image when the input image does not match the width and height in img2img.
  - Handle invalid parameters, e.g., stable diffusion.cpp only supports some wtype.
  - Release context resource
  - Add more tests to test different parameters, e.g., VAE model, with LoRA ...
  - [Current tests](https://github.com/grorge123/WasmEdge/blob/stable-diffusion/test/plugins/wasmedge_stablediffusion/wasmedge_stablediffusion.cpp) only cover Convert, Txt2img, and Img2img.
  - Finish documentation including install tutorial, a running example, and Rust crate documentation.
  - Create functions to set call stable diffusion plugin parameters in the Rust crate

- [x] (M4) [2 weeks] Document writing
- Continue to build sample application and write sample documentation, refer to LlamaEdge.

- [x] (M5) [1 week] Test optimization
- Test and optimize host function and sample application, and improve documentation.

- [ ] (M6) [2 weeks] Merge
- Merge stable-diffusion.cpp fork upward and integrate it into the project.

# Reference

- https://summer-ospp.ac.cn/org/prodetail/248830517?lang=zh&list=pro
- https://github.com/WasmEdge/WasmEdge/issues/3369
- https://github.com/WasmEdge/WasmEdge/issues/3405
- https://github.com/WasmEdge/WasmEdge/pull/3444
- https://github.com/grorge123/wasmedge-stable-diffusion

CC @dm4

**Comment by hydai** [comment]
Hi @Tenderyi 
Before the OSPP started, @grorge123 had already contributed some implementations and designs for stable diffusion.cpp plugin. See: https://github.com/WasmEdge/WasmEdge/issues/3405

It provides the basic stable diffusion.cpp APIs for supporting some features and a basic Rust SDK and an example.

It would be better to build the plugin based on the previous implementation. WDYT?

**Comment by hydai** [comment]
The merged PR: https://github.com/WasmEdge/WasmEdge/pull/3444
The Rust SDK and examples: https://github.com/grorge123/wasmedge-stable-diffusion

**Comment by Tenderyi** [comment]
Thanks a lot! That would be helpful!

**Comment by dm4** [comment]
Hi @Tenderyi,
Not sure if there's anything you need to revise in your original milestones according to the content of PR #3444? We wanted to kindly follow up as we've observed that there hasn't been an update on the progress of this issue for a few weeks. Is there any support or assistance you might need?

**Comment by Tenderyi** [comment]
@dm4 I am so sorry for not updating the issue milestone! I have been doing research locally for the past few weeks, and I am currently organizing the materials. I promise to update the issue with the progress tomorrow or the day after tomorrow.

**Comment by Tenderyi** [comment]
### Process:
- Reproduced the project of issue [#3405](https://github.com/WasmEdge/WasmEdge/issues/3405) and successfully ran its Rust instance. To ensure the integrity of the original project, I plan to clone the project to my github repository and update it synchronously. The address is https://github.com/Tenderyi/wasmedge-stable-diffusion.

- Some interface functions have been added to the pr [#3444](https://github.com/WasmEdge/WasmEdge/pull/3444), but there is no rust implementation yet, so I have written rust call examples for the existing interfaces.

### Parameter settings to be update:
- [ ] -h, --help                                    show this help message and exit<br>
- [x] -M, --mode [MODEL]                    run mode (txt2img or img2img or convert, default: txt2img)
- [ ] -t, --threads N                             number of threads to use during computation (default: -1).If threads <= 0, then threads will be set to the number of CPU physical cores
- [x] -m, --model [MODEL]                   path to model
- [ ] --vae [VAE]                                 path to vae
- [ ] --taesd [TAESD_PATH]                 path to taesd. Using Tiny AutoEncoder for fast decoding (low quality)
- [ ] --control-net [CONTROL_PATH]     path to control net model
- [ ] --embd-dir [EMBEDDING_PATH]    path to embeddings.
- [ ] --stacked-id-embd-dir [DIR]          path to PHOTOMAKER stacked id embeddings.
- [ ] --input-id-images-dir [DIR]           path to PHOTOMAKER input id images dir.
- [ ] --normalize-input                         normalize PHOTOMAKER input id images
- [ ] --upscale-model [ESRGAN_PATH]   path to esrgan model. Upscale images after generate, just RealESRGAN_x4plus_anime_6B supported by now.
- [ ] --upscale-repeats                         Run the ESRGAN upscaler this many times (default 1)
- [ ] --type [TYPE]                              weight type (f32, f16, q4_0, q4_1, q5_0, q5_1, q8_0)If not specified, the default is the type of the weight file.
- [ ] --lora-model-dir [DIR]                   lora model directory
- [x] -i, --init-img [IMAGE]                   path to the input image, required by img2img
- [ ] --control-image [IMAGE]               path to image condition, control net
- [x] -o, --output OUTPUT                    path to write result image to (default: ./output.png)
- [x] -p, --prompt [PROMPT]                 the prompt to render
- [ ] -n, --negative-prompt PROMPT      the negative prompt (default: "")
- [ ] --cfg-scale SCALE                        unconditional guidance scale: (default: 7.0)
- [ ] --strength STRENGTH                   strength for noising/unnoising (default: 0.75)
- [ ] --style-ratio STYLE-RATIO             strength for keeping input identity (default: 20%)
- [ ] --control-strength STRENGTH        strength to apply Control Net (default: 0.9) 1.0 corresponds to full destruction of information in init image
- [ ] -H, --height H                              image height, in pixel space (default: 512)
- [ ] -W, --width W                              image width, in pixel space (default: 512)
- [ ] --sampling-method {euler, euler_a, heun, dpm2, dpm++2s_a, dpm++2m, dpm++2mv2, lcm}                                                                sampling method (default: "euler_a")
- [ ] --steps  STEPS                             number of sample steps (default: 20)
- [ ] --rng {std_default, cuda}              RNG (default: cuda)
- [ ] -s SEED, --seed SEED                   RNG seed (default: 42, use random seed for < 0)
- [ ] -b, --batch-count COUNT              number of images to generate.
- [ ] --schedule {discrete, karras, ays}  Denoiser sigma schedule (default: discrete)
- [ ] --clip-skip N                                ignore last layers of CLIP network; 1 ignores none, 2 ignores one layer (default: -1), <= 0 represents unspecified, will be 1 for SD1.x, 2 for SD2.x
- [ ] --vae-tiling                                  process vae in tiles to reduce memory usage
- [ ] --control-net-cpu                         keep controlnet in cpu (for low vram)
- [ ] --canny                                      apply canny preprocessor (edge detection)
- [ ] --color                                        Colors the logging tags according to level
- [ ] -v, --verbose                               print extra info

**Comment by hydai** [comment]
Please use `fork` instead of manually re-adding the codes. It lost its previous history.
To add these new features to the upstream, you simply need to submit a PR to the original repository.

What's the output? It can be strange if the temperature or prompt are not the same.

**Comment by Tenderyi** [comment]
Thanks for your advice!! I've already fork the project, the newset repository is https://github.com/Tenderyi/wasmedge-stable-diffusion.
Beside, althougth I run the example of the issue https://github.com/WasmEdge/WasmEdge/issues/3405 by setting the prompt, the output is still an empty picture colored red which rgb is(127,0,0). And I'm trying to find it out.

**Comment by hydai** [comment]
> Beside, althougth I run the example of the issue https://github.com/WasmEdge/WasmEdge/issues/3405 by setting the prompt, the output is still an empty picture colored red which rgb is(127,0,0). And I'm trying to find it out.

It sounds weird. I can run the demo without issue. Could you share the detailed commands you used here so I can check for any potential problems?

**Comment by Tenderyi** [comment]
```
cargo build --target wasm32-wasi --release
wasmedge --dir .:. ./target/wasm32-wasi/release/wasmedge_stable_diffusion_example.wasm
```
Just like that.
If it can work well, I supports it maybe caused by the environment ?? I am trying to rebuild the env.

**Comment by Tenderyi** [comment]
Thanks a lot! It works after rebuilding the env.

**Comment by hydai** [comment]
Hi @Tenderyi 
It has been two weeks since you updated the progress. Do you encounter any issues that we can help with?

**Comment by Tenderyi** [comment]
I'm very sorry, because I have too many things to do in school recently, so my progress is a bit slow. The work of the last stage is basically completed, but there are still some bugs to debug. I will follow the task arrangement in the milestone and synchronize the local work to GitHub before next Monday.

**Comment by Tenderyi** [comment]
### Process:

- Support for console commands has been updated to https://github.com/WasmEdge/WasmEdge/issues/3529#issuecomment-2248887875.

- Added support for CLI parameters `--clip_on_cpu` and `--vae_on_cpu`. They are currently supported in the latest version of Stable Diffusion.cpp.

### Parameters that are not currently implemented include:

Parameters used to transform the model

- --vae [VAE]
- --type [TYPE]

Parameters for scaling images

- -H, --height H
- -W, --width W

Parameters for ESRGAN

- --upscale-model [ESRGAN_PATH]
- --upscale-repeats

Functions that need to be refined

- -t, --threads N
- --control-image [IMAGE]
- --control-net [CONTROL_PATH]
- -b, --batch-count COUNT
- --canny

Less critical parameters

- -h, --help
- --color
- -v, --verbose

### Remark
I implemented the command line parameters in rust in the demo project. In addition, I would like to know whether all these parameters need to be implemented.

**Comment by hydai** [comment]
We can skip `-h, --help` because users will never call this function via the sd.cpp plugin.
Do you have any other unnecessary options?

**Comment by Tenderyi** [comment]
By now, I've already support txt2img, img2img, and most of the options, except `--color` (Maybe it's unnecessary ?) and `--verbose`.(Maybe it's unnecessary?)
In this week, I will optimize host function and sample application, and improve documentation.

**Comment by hydai** [comment]
Let's ignore `--color` and `--verbose` for now.

**Comment by hydai** [comment]
Also, do you have the lora related examples? I think it's a very important feature if we can have a demo for it.

**Comment by dm4** [comment]
Hello @Tenderyi , there's another pull request that needs you to resolve conflicts: https://github.com/WasmEdge/wasmedge-stable-diffusion/pull/9. Due to the limitations of the OSPP system, if the pull request cannot be merged, I won't be able to provide a passing review in OSPP. The system shows the following message:

> Pull request (#2) failed to merge, please re-examine your pull request(s) and submit again.

**Comment by Tenderyi** [comment]
> Hello @Tenderyi , there's another pull request that needs you to resolve conflicts: [WasmEdge/wasmedge-stable-diffusion#9](https://github.com/WasmEdge/wasmedge-stable-diffusion/pull/9). Due to the limitations of the OSPP system, if the pull request cannot be merged, I won't be able to provide a passing review in OSPP. The system shows the following message:
> 
> > Pull request (#2) failed to merge, please re-examine your pull request(s) and submit again.

That's for sure. I've already resolve conflicts, and it can run successfully.

**Comment by hydai** [comment]
Completed, closing it.
