### ISSUE TITLE
LFX Workspace: WASM Serializer with new proposals

### ISSUE THREAD

**Issue by elhewaty** [WasmEdge/WasmEdge#3722]
### Project Title

WASM Serializer with new proposals

### Motivation

After implementing the `function-references`, `GC`, `relaxed-SIMD`,  and `exception handling` proposals, the serializer doesn't know about them, so we need to implement them in the serializer.

### Expected Outcome

- Complete the serialization of the new module extensions in WASM proposals.
- Complete the serialization of the new instructions added in WASM proposals.
- Add some basic unit tests with hand-written WASM binaries.

### Details

WasmEdge has a WASM module serializer that converts the loaded WASM structure blocks into their binary format. After the great work of implementing the new proposals: `function-references`, `GC`, `relaxed-SIMD`,  and `exception handling`, we need to add them to the serializer. 

### Milestones

The LFX is a 12-week program and we have four proposals so I am planning initially that every proposal takes 3 weeks (maybe more or less):

- [x] (M1) [1 week] Get a deep understanding of the project and ask so many questions.
- [x] (M2) [2 weeks] Implement the `function-references` proposal and add tests.  PRs: [3748](https://github.com/WasmEdge/WasmEdge/pull/3748), [3795](https://github.com/WasmEdge/WasmEdge/pull/3759)
- [x] (M3) [3 weeks] Implement the `GC` proposal and add tests PRs: [3821](https://github.com/WasmEdge/WasmEdge/pull/3821), [3865](https://github.com/WasmEdge/WasmEdge/pull/3865)
- [x] (M4) [3 weeks] Implement the `relaxed-SIMD` proposal and add tests. PR: [3800](https://github.com/WasmEdge/WasmEdge/pull/3800)
- [x] (M5) [3 weeks] Implement the `exception handling` proposal and add tests. PR: [3876](https://github.com/WasmEdge/WasmEdge/pull/3876)

We may divide these milestones into sub-milestones later, but this is good as a start.

### Appendix

Original issue: https://github.com/WasmEdge/WasmEdge/issues/3585

**Comment by elhewaty** [comment]
@q82419 @hydai 
While studying the serializer code, the code implements the binary format from the standards: [this](https://github.com/WasmEdge/WasmEdge/blob/master/lib/loader/serialize/serial_section.cpp#L13)  implements [that](https://webassembly.github.io/spec/core/binary/modules.html#custom-section). 

I can't find something similar for the function references. 

from the function reference proposal
>Add a new form of typed reference type ref $t and a nullable variant (ref null $t), where $t is a type index; can be used as both a value type or an element type for tables

these types are already added in the `enum.inc`:
>T(Ref, 0x64, "ref") 
T(RefNull, 0x63, "ref_null") 

[here](https://github.com/WasmEdge/WasmEdge/blob/master/lib/loader/serialize/serial_type.cpp#L46-L57), Can you please what is needed to be done (If possible )?

**Comment by hydai** [comment]
Hi @elhewaty 
If all types[1] are handled, then we can continue with the other proposals.

[1]: https://github.com/WebAssembly/function-references/blob/main/proposals/function-references/Overview.md#binary-format

**Comment by elhewaty** [comment]
I think @q82419 implemented them [here](https://github.com/WasmEdge/WasmEdge/pull/2691).

**Comment by q82419** [comment]
Maybe some trivial parts are done when I implemented the proposal.
It's fine and wish that you can help to confirm the correctness and add some testing data. Thanks!

**Comment by q82419** [comment]
> @q82419 @hydai While studying the serializer code, the code implements the binary format from the standards: [this](https://github.com/WasmEdge/WasmEdge/blob/master/lib/loader/serialize/serial_section.cpp#L13) implements [that](https://webassembly.github.io/spec/core/binary/modules.html#custom-section).
> 
> I can't find something similar for the function references.
> 
> from the function reference proposal
> 
> > Add a new form of typed reference type ref $t and a nullable variant (ref null $t), where $t is a type index; can be used as both a value type or an element type for tables
> 
> these types are already added in the `enum.inc`:
> 
> > T(Ref, 0x64, "ref")
> > T(RefNull, 0x63, "ref_null")
> 
> [here](https://github.com/WasmEdge/WasmEdge/blob/master/lib/loader/serialize/serial_type.cpp#L46-L57), Can you please what is needed to be done (If possible )?

You can refer to the pattern [here](https://github.com/WasmEdge/WasmEdge/blob/master/include/common/types.h#L63-L85):

For old types such as `func $t` and `externref $e`, we all migrated into `ref null $t` and `ref null $e` when loading.
Oppositely, when serializing that cases, if it detected the `ref null $t` and `ref null $e`, the serializer can output the `func $t` and `externref $e` for the compatibility.

**Comment by q82419** [comment]
@elhewaty Please record your PR #3759 in this issue.

**Comment by elhewaty** [comment]
@q82419, I think relaxed-SIMD instructions were handled here https://github.com/WasmEdge/WasmEdge/pull/3311, We only need to add tests, what do you think?

**Comment by q82419** [comment]
@elhewaty I think you can study the GC proposal next.
Besides the new instructions, the GC proposal has more complexity due to the extended types in module.

**Comment by q82419** [comment]
Comment:

Completed the mid-term evaluation.
The remain parts (GC, Exception-Handling) are for the final evaluation.

**Comment by q82419** [comment]
@elhewaty
Here's the information about the exception-handling proposal.
You can find out that there are some `LEGACY-EH` tag comments.
That's because we also supported some parts of legacy version of exception-handling proposal, which will be removed in the future.
When implementing, you can ignore all `LEGACY-EH` related parts.

**Comment by elhewaty** [comment]
@q82419  I finished adding the exception handling proposal. but I can't find the op code for `catch_ref` and `catch_all_ref`.

**Comment by q82419** [comment]
> @q82419 I finished adding the exception handling proposal. but I can't find the op code for `catch_ref` and `catch_all_ref`.

https://webassembly.github.io/exception-handling/core/binary/instructions.html#control-instructions
Because it became the flag of the catch clause in the try_table.

**Comment by q82419** [comment]
Comment:

Completed the final evaluation.
Congratulations and thanks a lot!
