### ISSUE TITLE
feat: Upgrade Ubuntu latest from 22.04 to 24.04

### ISSUE THREAD

**Issue by 0yi0** [WasmEdge/WasmEdge#3847]
### Summary

- [x] Prepare docker images for Ubuntu 24.04 #3774
- [x] Fix errors on new docker images
  * #3819
  * #3836
  * #3863
- [x] Update CI workflows #3859
- [x] Update related docs
  - [x] [.github/workflows/README.md](https://github.com/WasmEdge/WasmEdge/blob/master/.github/workflows/README.md) #3874
  - [x] WasmEdge/docs#256
  - [x] [WasmEdge overview on Docker Hub](https://hub.docker.com/repository/docker/wasmedge/wasmedge/general)

### Appendix

Note: The changes should not affect the release of WasmEdge, because Ubuntu latest is only used for testing on our Github workflows.
