### ISSUE TITLE
LFX Workspace: Support WASI-Crypto proposal

### ISSUE THREAD

**Issue by hydai** [WasmEdge/WasmEdge#410]
## Motivation

This is an umbrella issue for WASI-Crypto.

## Details

@sonder-joker Please describe your milestones in this issue.

**Comment by sonder-joker** [comment]
# Milestones

The WASI Cryptography API contain  

1. The basic of wasi-crypto: 1~2 weeks.
   * Dive into the proposal of wasi-crypto
   * Integrate wasi-crypto's witx
   * Transform it into header file

2. Implement the detail of wasi-crypto: 6 weeks.
   * Common types and functions
   * Symmetric operations
   * Common types and functions for asymmetric operations
   * Signatures
   * Key exchange
   * External secrets

3. Expose interface by binding sdk: 1 weeks.

# Future work
* Write a document record the basic useage of crypto interface
* Try to bind openssl library and test performance.


# Appendices

* [WebAssembly/wasi-crypto](https://github.com/WebAssembly/wasi-crypto)

# Work progress
https://github.com/WasmEdge/WasmEdge/pull/408

**Comment by sonder-joker** [comment]
# An expermental cpp backend for witx-codegen(https://github.com/jedisct1/witx-codegen/pull/11)
Accroding to https://github.com/WebAssembly/wasi-crypto/issues/35, witx will have abi-change in future, which adopt by wasi-crypto. So I write a expermental cpp backend's codegen for it.

**Comment by sonder-joker** [comment]
# Week 3
I have partly implement [Common types and functions](
https://github.com/WasmEdge/WasmEdge/pull/408/commits/e157f284a494b1a7ad61b56dd64ec91fe3cf82fd). But I should implement entiry module in this week.  I believe that I just need one day more to finsh it. Will update description after I finish it.

**Comment by sonder-joker** [comment]
# Week 2
~This is what I missing to record~
* Just need to generate enum/struct/union instead of function prototype. The pull request in witx-codegen will delay(But I will finish it later)
* ...

**Comment by sonder-joker** [comment]
This Week:

**Comment by sonder-joker** [comment]
# This week

**Comment by sonder-joker** [comment]
# This week 
- [ ] Implementation the symmetric module's thread safe. [OpenSSL is thread safe since 1.1.0](https://www.openssl.org/blog/blog/2017/02/21/threads/)
- [ ] Consider the implementation alternative symmetric algorithm lack in OpenSSL: xoodyak and chacha_poly
- [ ] Add OpenSSL environment variable in build/dev environment
- [ ] Add more detailed description in commont and doc. Now comment is disorganized
- [ ] Symmetric module use some deprecated fun in OpenSSL 3.0. Consider replace them by EVP interface.
- [ ] The Hkdf algorithm have bug to fix.

**Comment by jedisct1** [comment]
This is pretty amazing work! 🎉

ChaChaPoly is required for TLS 1.3, so it is likely to be supported by OpenSSL.

**Comment by sonder-joker** [comment]
> This is pretty amazing work! 🎉
> 
> ChaChaPoly is required for TLS 1.3, so it is likely to be supported by OpenSSL.

Thanks for your encourage and help! I have found the relative implementation about Chacha in OpenSSL . Besides, yours great implmentation of wasi crypto inspired me a lot!

**Comment by sonder-joker** [comment]
#This Week
For previous week
- [x] Finish the asymmetric common module.
- [x] Sparate OpenSSL from internel. I think I can make a more elegant way like `engine` but need some time.
- [x] Most of design part in key_exchange and signature module .  

For this week:
- [ ]  Work on key_exchange and signature module's crytpo implementation.
- [ ]  Previously unfinished questions.

**Comment by sonder-joker** [comment]
# This Week
- [ ]  Meet some issue about thread safe. It not affect current work but need solve.
- [ ]  If I missing some algorithms need to implement?
- [ ]  This week will work on signature module.

**Comment by sonder-joker** [comment]
# This Week 
Already finish most of feature. 
1. Recheck return error code.
2. Refactor most of design.
3. Can add more unit test. 
4. Replace `std::optional<std::shared_ptr<T>>` with `std::shared_ptr<T>` for optional
5. Replace rust-like lock design with c++ lock design. Thre previous way would get a `std::optional<std::shared_ptr<Mutex<std::unique_ptr<T>>>>` wrapper

**Comment by sonder-joker** [comment]
# This Week
Now the proposal implementation enters the final step.
- [ ] Some TODO in code
- [ ] Export SDK
- [ ] Add more detailed comment on code
- [ ] Create doc about how to use this module in WasmEdge.

[All necessary algorithms have been implemented except the recommended three algorithms](https://github.com/WebAssembly/wasi-crypto/blob/main/docs/wasi-crypto.md#algorithms)

**Comment by jedisct1** [comment]
Congrats!

**Comment by q82419** [comment]
Merged: #1590
